export const TEXT = {
  // Shared
  CANCEL: 'Cancel',
  CLOSE: 'Close',
  CONFIRM_DELETE: 'Confirm delete',
  DELETE: 'Delete',
  DATE_PICKER_NEXT_MONTH_LABEL: '>',
  DATE_PICKER_PREVIOUS_MONTH_LABEL: '<',
  NAV_HOME_ACCESSIBILITY_LABEL: 'ไปหน้าหลัก',
  SHARED_ADD_THAI: 'เพิ่ม',
  SHARED_BACK_THAI: 'ย้อนกลับ',
  SHARED_BACK_TO_HOME_THAI: 'กลับหน้าหลัก',
  SHARED_CLOSE_THAI: 'ปิด',
  SHARED_DELETE_THAI: 'ลบ',
  SHARED_DEPARTMENT_LABEL: 'Department:',
  SHARED_EMPTY_DATA: 'ไม่มีข้อมูล',
  SHARED_ERROR_TITLE_THAI: 'เกิดข้อผิดพลาด',
  SHARED_HISTORY: 'History',
  SHARED_LOADING_DATA_TITLE: 'กำลังโหลดข้อมูล',
  SHARED_LOADING_DESCRIPTION: 'กรุณารอสักครู่',
  SHARED_LOADING_HISTORY: 'Loading history',
  SHARED_MODAL: 'Modal',
  SHARED_NO_HISTORY: 'No history',
  SHARED_PLEASE_WAIT_A_MOMENT: 'Please wait a moment',
  SHARED_REQUIRED_INFORMATION: 'ข้อมูลที่จำเป็น',
  SHARED_RETRY: 'Retry',
  SHARED_RETRY_THAI: 'ลองใหม่',
  SHARED_SEARCH_NAME_PLACEHOLDER: 'ค้นหาชื่อ',
  SHARED_SOMETHING_WENT_WRONG: 'Something went wrong',
  SHARED_SUCCESS: 'Success',
  SHARED_UNABLE_TO_COMPLETE: 'Unable to complete',
  SHARED_UNABLE_TO_LOAD_HISTORY: 'Unable to load history',
  SHARED_UPDATE: 'Update',
  SHARED_UPDATING: 'Updating...',

  // Home
  HOME_LOADING_NEWS_TITLE: 'กำลังโหลดข่าวสาร',
  HOME_MENU_SECTION_DESCRIPTION: 'เลือกเมนูที่ต้องการใช้งาน',
  HOME_MENU_SECTION_TITLE: 'เมนู',
  HOME_NEWS_SECTION_TITLE: 'ข่าวสาร',
  HOME_NO_NEWS_MESSAGE: 'ไม่พบข่าวสาร',
  HOME_TITLE: 'หน้าหลัก',

  // Auth
  AUTH_LOGIN: 'Login',
  AUTH_LOGIN_FAILED: 'เข้าสู่ระบบไม่สำเร็จ',
  AUTH_SIGNING_IN_TITLE: 'กำลังเข้าสู่ระบบ',

  // absence
  absence_APPROVER_LABEL: 'ผู้อนุมัติ',
  absence_APPROVER_PLACEHOLDER: 'เลือกผู้อนุมัติ',
  absence_BIRTH_TITLE: 'ลาคลอด',
  absence_BUSINESS_FORM_TITLE: 'แบบฟอร์มไปราชการ',
  absence_BUSINESS_SUBMIT_SUCCESS_MESSAGE: 'Business absence request submitted successfully.',
  absence_BUSINESS_TITLE: 'ลากิจส่วนตัว',
  absence_BIRTH_SUBMIT_SUCCESS_MESSAGE: 'Birth absence request submitted successfully.',
  absence_CANNOT_REQUEST_TITLE: 'ไม่สามารถทำเรื่องลาได้',
  absence_CONFIRM_REMOVE_MESSAGE: 'Please confirm before removing this absence request.',
  absence_CONFIRM_REMOVE_TITLE: 'Confirm remove request',
  absence_CONFIRM_SUBMIT_ACTION: 'Confirm',
  absence_CONFIRM_SUBMIT_CANCEL: 'Cancel',
  absence_CONFIRM_SUBMIT_MESSAGE: 'Please confirm before submitting this absence request.',
  absence_CONFIRM_SUBMIT_TITLE: 'Confirm absence request',
  absence_CONTACT_CHANNEL_LABEL: 'ช่องทางติดต่อ',
  absence_CONTACT_CHANNEL_PLACEHOLDER: 'กรอกช่องทางติดต่อ',
  absence_DAY_UNIT: 'วัน',
  absence_DELEGATE_LABEL: 'ผู้รับมอบหมาย',
  absence_DELEGATE_PLACEHOLDER: 'เลือกผู้รับมอบหมาย',
  absence_END_DATE_LABEL: 'วันที่สิ้นสุด',
  absence_HALF_DAY_FIRST_AFTERNOON: 'วันแรกครึ่งวันบ่าย',
  absence_HALF_DAY_FIRST_AFTERNOON_LAST_MORNING: 'วันแรกครึ่งวันบ่าย - วันสุดท้ายครึ่งวันเช้า',
  absence_HALF_DAY_FIRST_MORNING: 'วันแรกครึ่งวันเช้า',
  absence_HALF_DAY_LABEL: 'ลาครึ่งวัน',
  absence_HALF_DAY_LAST_MORNING: 'วันสุดท้ายครึ่งวันเช้า',
  absence_HALF_DAY_NONE: '-',
  absence_HALF_DAY_PLACEHOLDER: 'เลือกตัวเลือกลาครึ่งวัน',
  absence_HISTORY_TAB_TITLE: 'ประวัติ',
  absence_HISTORY_TITLE: 'ประวัติการลา',
  absence_INIT_LOAD_ERROR_MESSAGE: 'ไม่สามารถโหลดข้อมูลตั้งต้นได้',
  absence_INITIAL_DATA_LOADED: 'โหลดข้อมูลตั้งต้นเรียบร้อยแล้ว',
  absence_INVALID_WEEKEND_DATE_MESSAGE: 'Please select Monday to Friday.',
  absence_INVALID_WEEKEND_DATE_TITLE: 'Invalid date',
  absence_LEAVE_DATE_LABEL: 'วันที่ลา',
  absence_LEAVE_DAY_COUNT_LABEL: 'จำนวนวันลา',
  absence_MEDICAL_CERTIFICATE_ACTION: 'Choose file',
  absence_MEDICAL_CERTIFICATE_LABEL: 'Medical certificate',
  absence_MEDICAL_CERTIFICATE_PLACEHOLDER: 'No file selected',
  absence_MEDICAL_CERTIFICATE_REMOVE: 'Remove file',
  absence_PERMISSION_REQUIRED_MESSAGE: 'Permission to access your photo library is required.',
  absence_PERMISSION_REQUIRED_TITLE: 'Permission required',
  absence_REASON_LABEL: 'เหตุผล',
  absence_REASON_PLACEHOLDER: 'กรอกเหตุผล',
  absence_RELAX_FORM_TITLE: 'แบบฟอร์มลาพักผ่อน',
  absence_RELAX_SUBMIT_SUCCESS_MESSAGE: 'Relax absence request submitted successfully.',
  absence_RELAX_TITLE: 'ลาพักผ่อน',
  absence_REQUEST_TYPE_PROMPT: 'เลือกประเภทการลา',
  absence_SELECT_DATE_HINT: 'เลือกวันที่เริ่มต้นและวันที่สิ้นสุด',
  absence_SICK_FORM_TITLE: 'แบบฟอร์มลาป่วย',
  absence_SICK_SUBMIT_ERROR_MESSAGE: 'Unable to submit sick leave request.',
  absence_SICK_SUBMIT_SUCCESS_MESSAGE: 'Sick leave request submitted successfully.',
  absence_SICK_TITLE: 'ลาป่วย',
  absence_START_DATE_LABEL: 'วันที่เริ่มต้น',
  absence_SUBMIT_ERROR_MESSAGE: 'Unable to submit absence request.',
  absence_SUBMIT_REQUEST: 'ส่งคำขอ',
  absence_SUBMITTING_LABEL: 'Submitting...',
  absence_TITLE: 'การลา',
  absence_TRAVEL_DETAIL_LABEL: 'รายละเอียดการเดินทาง',
  absence_TRAVEL_DETAIL_PLACEHOLDER: 'กรอกรายละเอียดการเดินทาง',
  absence_VALIDATION_AGENT_REQUIRED: 'กรุณาเพิ่มผู้รับมอบหมายอย่างน้อย 1 คน',
  absence_VALIDATION_APPROVER_REQUIRED: 'กรุณาเลือกผู้อนุมัติ',
  absence_VALIDATION_CONTACT_REQUIRED: 'กรุณากรอกช่องทางติดต่อ',
  absence_VALIDATION_DATE_REQUIRED: 'กรุณาเลือกวันที่ลา',
  absence_VALIDATION_END_DATE_AFTER_START: 'วันที่สิ้นสุดต้องไม่ก่อนวันที่เริ่มต้น',
  absence_VALIDATION_END_DATE_NOT_FUTURE: 'วันที่สิ้นสุดต้องไม่เกินวันนี้',
  absence_VALIDATION_REASON_REQUIRED: 'กรุณากรอกเหตุผล',
  absence_VALIDATION_START_DATE_NOT_FUTURE: 'วันที่เริ่มต้นต้องไม่เกินวันนี้',
  absence_VALIDATION_START_DATE_NOT_PAST: 'วันที่เริ่มต้นต้องเป็นวันนี้หรือวันถัดไป',
  absence_WAITING_TITLE: 'รออนุมัติ',

  // Meeting
  MEETING_HEADER_TITLE: 'Meeting',
  MEETING_INCOMING: 'Incoming Meeting',
  MEETING_LOADING_MEETINGS: 'Loading meetings',
  MEETING_MENU_TITLE: 'ประชุม',
  MEETING_NO_HISTORY: 'No meeting history',
  MEETING_NO_INCOMING_MEETINGS: 'No incoming meetings',
  MEETING_NO_MEETINGS_TODAY: 'No meetings today',
  MEETING_TODAY: 'Today Meeting',
  MEETING_UNABLE_TO_LOAD_MEETINGS: 'Unable to load meetings',

  // Repair Computer
  REPAIR_COMPUTER_APPROVEMENT: 'Approvement',
  REPAIR_COMPUTER_APPROVEMENT_DESCRIPTION: 'Approve repair computer job outcomes.',
  REPAIR_COMPUTER_ASSIGN_CONFIRM: 'Assign Confirm',
  REPAIR_COMPUTER_BACK_TO_CURRENT_JOB: 'Back to Current Job',
  REPAIR_COMPUTER_CANNOT_INFORM_JOB: 'Cannot inform job',
  REPAIR_COMPUTER_CHECKING_PRIVILEGE: 'Checking privilege',
  REPAIR_COMPUTER_CHECKING_REQUEST: 'Checking request',
  REPAIR_COMPUTER_CURRENT_JOB: 'Current Job',
  REPAIR_COMPUTER_DELETE_CONFIRM_MESSAGE: 'Do you want to delete this repair computer job?',
  REPAIR_COMPUTER_DETAIL: 'Detail',
  REPAIR_COMPUTER_DETAIL_LABEL: 'Detail:',
  REPAIR_COMPUTER_EDIT_JOB: 'Edit Job',
  REPAIR_COMPUTER_FOREMAN: 'Foreman',
  REPAIR_COMPUTER_INFORM: 'Inform',
  REPAIR_COMPUTER_INFORM_DATE_LABEL: 'Inform Date:',
  REPAIR_COMPUTER_JOB_DELETED_SUCCESS_MESSAGE: 'Repair job deleted successfully.',
  REPAIR_COMPUTER_JOB_DETAIL: 'Job Detail',
  REPAIR_COMPUTER_JOB_ID_LABEL: 'Job ID:',
  REPAIR_COMPUTER_JOB_UPDATED_SUCCESS_MESSAGE: 'Repair computer job updated successfully.',
  REPAIR_COMPUTER_JOBS: 'Jobs',
  REPAIR_COMPUTER_LOADING_CURRENT_JOBS: 'Loading current jobs',
  REPAIR_COMPUTER_LOADING_DETAIL: 'Loading detail',
  REPAIR_COMPUTER_LOADING_JOB_DETAIL: 'Loading job detail',
  REPAIR_COMPUTER_LOADING_MANAGE_JOBS: 'Loading manage jobs',
  REPAIR_COMPUTER_LOADING_NEW_JOBS: 'Loading new jobs',
  REPAIR_COMPUTER_LOADING_QUEUE: 'Loading queue',
  REPAIR_COMPUTER_MANAGE_JOB: 'Manage Job',
  REPAIR_COMPUTER_MENU_TITLE: 'แจ้งซ่อมคอมพิวเตอร์',
  REPAIR_COMPUTER_NEW_JOB: 'New Job',
  REPAIR_COMPUTER_NO_CURRENT_JOBS: 'No current jobs',
  REPAIR_COMPUTER_NO_JOBS_TO_MANAGE: 'No jobs to manage',
  REPAIR_COMPUTER_NO_NEW_JOBS: 'No new jobs',
  REPAIR_COMPUTER_NO_WORKER_QUEUE: 'No worker queue',
  REPAIR_COMPUTER_PHONE: 'Phone',
  REPAIR_COMPUTER_PHONE_LABEL: 'Phone:',
  REPAIR_COMPUTER_QUEUE: 'Queue',
  REPAIR_COMPUTER_REJECT_DETAIL_LABEL: 'Reject Detail:',
  REPAIR_COMPUTER_REQUEST_SUBMITTED_SUCCESS_MESSAGE: 'Repair computer request submitted successfully.',
  REPAIR_COMPUTER_SELECT_ROLE: 'Select Role',
  REPAIR_COMPUTER_STATUS_LABEL: 'Status:',
  REPAIR_COMPUTER_SUPPLY_CODE: 'Supply Code',
  REPAIR_COMPUTER_SUPPLY_CODE_LABEL: 'Supply Code:',
  REPAIR_COMPUTER_TITLE: 'Repair Computer',
  REPAIR_COMPUTER_UNABLE_TO_DELETE_JOB: 'Unable to delete repair job.',
  REPAIR_COMPUTER_UNABLE_TO_LOAD_CURRENT_JOBS: 'Unable to load current jobs',
  REPAIR_COMPUTER_UNABLE_TO_LOAD_JOB_DETAIL: 'Unable to load job detail.',
  REPAIR_COMPUTER_UNABLE_TO_LOAD_MANAGE_JOBS: 'Unable to load manage jobs',
  REPAIR_COMPUTER_UNABLE_TO_LOAD_NEW_JOBS: 'Unable to load new jobs',
  REPAIR_COMPUTER_UNABLE_TO_LOAD_WORKER_QUEUE: 'Unable to load worker queue',
  REPAIR_COMPUTER_UNABLE_TO_OPEN_JOB_DETAIL: 'Unable to open job detail.',
  REPAIR_COMPUTER_UNABLE_TO_SUBMIT_REQUEST: 'Unable to submit repair computer request.',
  REPAIR_COMPUTER_UNABLE_TO_UPDATE_JOB: 'Unable to update repair computer job.',
  REPAIR_COMPUTER_USER_LABEL: 'User:',
  REPAIR_COMPUTER_WORKER: 'Worker',
  REPAIR_COMPUTER_WORKER_LABEL: 'Worker:',
  REPAIR_COMPUTER_VIEW_NEW_WORKER_JOBS_DESCRIPTION: 'View new repair computer jobs assigned to workers.',
  REPAIR_COMPUTER_VIEW_WORKER_CURRENT_JOBS_DESCRIPTION: 'View worker jobs currently in progress.',
  REPAIR_COMPUTER_VIEW_WORKER_HISTORY_DESCRIPTION: 'View worker repair computer job history.',

  // Calendar
  CALENDAR_DESCRIPTION: 'หน้านี้คือหน้าปฏิทิน',
  CALENDAR_TITLE: 'ปฏิทิน',

  // Person Search
  PERSON_SEARCH_DESCRIPTION: 'หน้านี้คือหน้าค้นหาบุคลากร',
  PERSON_SEARCH_TITLE: 'ค้นหาบุคลากร',

  // Forgot Timestamp
  FORGOT_TIMESTAMP_DESCRIPTION: 'หน้านี้คือหน้าลืมลงเวลา',
  FORGOT_TIMESTAMP_TITLE: 'ลืมลงเวลา',

  // Modal
  MODAL_TITLE: 'หน้าต่างโมดัล',
} as const;
