export const TEXT = {
  // Shared
  CANCEL: 'ยกเลิก',
  CLOSE: 'ปิด',
  CONFIRM_DELETE: 'ยืนยันการลบ',
  DELETE: 'ลบ',
  DATE_PICKER_NEXT_MONTH_LABEL: '>',
  DATE_PICKER_PREVIOUS_MONTH_LABEL: '<',
  NAV_HOME_ACCESSIBILITY_LABEL: 'ไปหน้าหลัก',
  SHARED_ADD_THAI: 'เพิ่ม',
  SHARED_BACK_THAI: 'ย้อนกลับ',
  SHARED_BACK_TO_HOME_THAI: 'กลับหน้าหลัก',
  SHARED_CLOSE_THAI: 'ปิด',
  SHARED_DELETE_THAI: 'ลบ',
  SHARED_DEPARTMENT_LABEL: 'แผนก:',
  SHARED_EMPTY_DATA: 'ไม่มีข้อมูล',
  SHARED_ERROR_TITLE_THAI: 'เกิดข้อผิดพลาด',
  SHARED_HISTORY: 'ประวัติ',
  SHARED_LOADING_DATA_TITLE: 'กำลังโหลดข้อมูล',
  SHARED_LOADING_DESCRIPTION: 'กรุณารอสักครู่',
  SHARED_LOADING_HISTORY: 'กำลังโหลดประวัติ',
  SHARED_MODAL: 'โมดัล',
  SHARED_NO_HISTORY: 'ไม่มีประวัติ',
  SHARED_GO_BACK: 'ย้อนกลับ',
  SHARED_OK: 'ตกลง',
  SHARED_PLEASE_WAIT_A_MOMENT: 'กรุณารอสักครู่',
  SHARED_REQUIRED_INFORMATION: 'ข้อมูลที่จำเป็น',
  SHARED_RETRY: 'ลองใหม่',
  SHARED_RETRY_THAI: 'ลองใหม่',
  SHARED_SEARCH_NAME_PLACEHOLDER: 'ค้นหาชื่อ',
  SHARED_SOMETHING_WENT_WRONG: 'เกิดข้อผิดพลาด',
  SHARED_SUCCESS: 'สำเร็จ',
  SHARED_UNABLE_TO_COMPLETE: 'ไม่สามารถดำเนินการได้',
  SHARED_UNABLE_TO_LOAD_HISTORY: 'ไม่สามารถโหลดประวัติได้',
  SHARED_UPDATE: 'อัปเดต',
  SHARED_UPDATING: 'กำลังอัปเดต...',

  // Home
  HOME_APP_NAME: 'Intania',
  HOME_CONFIRM_LOGOUT_TITLE: 'ยืนยันการออกจากระบบ',
  HOME_CONFIRM_LOGOUT_MESSAGE: 'คุณต้องการออกจากระบบนี้ใช่หรือไม่?',
  HOME_GREETING_MORNING: 'สวัสดีตอนเช้า',
  HOME_GREETING_AFTERNOON: 'สวัสดีตอนบ่าย',
  HOME_GREETING_EVENING: 'สวัสดีตอนเย็น',
  HOME_LOADING_NEWS_TITLE: 'กำลังโหลดข่าวสาร',
  HOME_LOGOUT: 'ออกจากระบบ',
  HOME_MENU_SECTION_DESCRIPTION: 'เลือกเมนูที่ต้องการใช้งาน',
  HOME_MENU_SECTION_TITLE: 'เมนู',
  HOME_NEWS_SECTION_TITLE: 'ข่าวสาร',
  HOME_NO_NEWS_MESSAGE: 'ไม่พบข่าวสาร',
  HOME_SEE_ALL_THAI: 'ดูทั้งหมด',
  HOME_SIGNING_OUT_TITLE: 'กำลังออกจากระบบ',
  HOME_TITLE: 'หน้าหลัก',
  HOME_WELCOME_DESCRIPTION: 'ระบบสำหรับบุคลากรมหาวิทยาลัยสงขลานครินทร์',

  // Auth
  AUTH_LOGIN: 'เข้าสู่ระบบ',
  AUTH_LOGIN_FAILED: 'เข้าสู่ระบบไม่สำเร็จ',
  AUTH_SIGNING_IN_TITLE: 'กำลังเข้าสู่ระบบ',

  // absence
  absence_APPROVER_LABEL: 'ผู้อนุมัติ',
  absence_APPROVER_PLACEHOLDER: 'เลือกผู้อนุมัติ',
  absence_BIRTH_TITLE: 'ลาคลอด',
  absence_BUSINESS_FORM_TITLE: 'แบบฟอร์มไปราชการ',
  absence_BUSINESS_SUBMIT_SUCCESS_MESSAGE: 'ส่งคำขอลากิจส่วนตัวสำเร็จ',
  absence_BUSINESS_TITLE: 'ลากิจส่วนตัว',
  absence_BIRTH_SUBMIT_SUCCESS_MESSAGE: 'ส่งคำขอลาคลอดสำเร็จ',
  absence_CANNOT_REQUEST_TITLE: 'ไม่สามารถทำเรื่องลาได้',
  absence_CONFIRM_REMOVE_MESSAGE: 'กรุณายืนยันก่อนลบคำขอการลานี้',
  absence_CONFIRM_REMOVE_TITLE: 'ยืนยันการลบคำขอ',
  absence_CONFIRM_SUBMIT_ACTION: 'ยืนยัน',
  absence_CONFIRM_SUBMIT_CANCEL: 'ยกเลิก',
  absence_CONFIRM_SUBMIT_MESSAGE: 'กรุณายืนยันก่อนส่งคำขอการลานี้',
  absence_CONFIRM_SUBMIT_TITLE: 'ยืนยันคำขอการลา',
  absence_CONTACT_CHANNEL_LABEL: 'ช่องทางติดต่อ',
  absence_CONTACT_CHANNEL_PLACEHOLDER: 'กรอกช่องทางติดต่อ',
  absence_DAY_UNIT: 'วัน',
  absence_DELEGATE_LABEL: 'ผู้รับมอบหมาย',
  absence_DELEGATE_PLACEHOLDER: 'เลือกผู้รับมอบหมาย',
  absence_END_DATE_LABEL: 'วันที่สิ้นสุด',
  absence_HALF_DAY_FIRST_AFTERNOON: 'วันแรกครึ่งวันบ่าย',
  absence_HALF_DAY_FIRST_AFTERNOON_LAST_MORNING: 'วันแรกครึ่งวันบ่าย - วันสุดท้ายครึ่งวันเช้า',
  absence_HALF_DAY_FIRST_MORNING: 'วันแรกครึ่งวันเช้า',
  absence_HALF_DAY_LABEL: 'ลาครึ่งวัน',
  absence_HALF_DAY_LAST_MORNING: 'วันสุดท้ายครึ่งวันเช้า',
  absence_HALF_DAY_NONE: '-',
  absence_HALF_DAY_PLACEHOLDER: 'เลือกตัวเลือกลาครึ่งวัน',
  absence_HISTORY_TAB_TITLE: 'ประวัติ',
  absence_HISTORY_TITLE: 'ประวัติการลา',
  absence_INIT_LOAD_ERROR_MESSAGE: 'ไม่สามารถโหลดข้อมูลตั้งต้นได้',
  absence_INITIAL_DATA_LOADED: 'โหลดข้อมูลตั้งต้นเรียบร้อยแล้ว',
  absence_INVALID_WEEKEND_DATE_MESSAGE: 'กรุณาเลือกวันจันทร์ถึงวันศุกร์',
  absence_INVALID_WEEKEND_DATE_TITLE: 'วันที่ไม่ถูกต้อง',
  absence_LEAVE_DATE_LABEL: 'วันที่ลา',
  absence_LEAVE_DAY_COUNT_LABEL: 'จำนวนวันลา',
  absence_MEDICAL_CERTIFICATE_ACTION: 'เลือกไฟล์',
  absence_MEDICAL_CERTIFICATE_LABEL: 'ใบรับรองแพทย์',
  absence_MEDICAL_CERTIFICATE_TOGGLE: 'แนบใบรับรองแพทย์',
  absence_MEDICAL_CERTIFICATE_PLACEHOLDER: 'ยังไม่ได้เลือกไฟล์',
  absence_MEDICAL_CERTIFICATE_REMOVE: 'ลบไฟล์',
  absence_PERMISSION_REQUIRED_MESSAGE: 'ต้องการสิทธิ์ในการเข้าถึงคลังภาพของคุณ',
  absence_PERMISSION_REQUIRED_TITLE: 'ต้องการสิทธิ์',
  absence_REASON_LABEL: 'เหตุผล',
  absence_REASON_PLACEHOLDER: 'กรอกเหตุผล',
  absence_RELAX_FORM_TITLE: 'แบบฟอร์มลาพักผ่อน',
  absence_RELAX_SUBMIT_SUCCESS_MESSAGE: 'ส่งคำขอลาพักผ่อนสำเร็จ',
  absence_RELAX_TITLE: 'ลาพักผ่อน',
  absence_REQUEST_TYPE_PROMPT: 'เลือกประเภทการลา',
  absence_SELECT_DATE_HINT: 'เลือกวันที่เริ่มต้นและวันที่สิ้นสุด',
  absence_SICK_FORM_TITLE: 'แบบฟอร์มลาป่วย',
  absence_SICK_SUBMIT_ERROR_MESSAGE: 'ไม่สามารถส่งคำขอลาป่วยได้',
  absence_SICK_SUBMIT_SUCCESS_MESSAGE: 'ส่งคำขอลาป่วยสำเร็จ',
  absence_SICK_TITLE: 'ลาป่วย',
  absence_START_DATE_LABEL: 'วันที่เริ่มต้น',
  absence_SUBMIT_ERROR_MESSAGE: 'ไม่สามารถส่งคำขอการลาได้',
  absence_SUBMIT_REQUEST: 'ส่งคำขอ',
  absence_SUBMITTING_LABEL: 'กำลังส่งคำขอ...',
  absence_TITLE: 'การลา',
  absence_TRAVEL_DETAIL_LABEL: 'รายละเอียดการเดินทาง',
  absence_TRAVEL_DETAIL_PLACEHOLDER: 'กรอกรายละเอียดการเดินทาง',
  absence_VALIDATION_AGENT_REQUIRED: 'กรุณาเพิ่มผู้รับมอบหมายอย่างน้อย 1 คน',
  absence_VALIDATION_APPROVER_REQUIRED: 'กรุณาเลือกผู้อนุมัติ',
  absence_VALIDATION_CONTACT_REQUIRED: 'กรุณากรอกช่องทางติดต่อ',
  absence_VALIDATION_DATE_REQUIRED: 'กรุณาเลือกวันที่ลา',
  absence_VALIDATION_END_DATE_AFTER_START: 'วันที่สิ้นสุดต้องไม่ก่อนวันที่เริ่มต้น',
  absence_VALIDATION_END_DATE_NOT_FUTURE: 'วันที่สิ้นสุดต้องไม่เกินวันนี้',
  absence_VALIDATION_REASON_REQUIRED: 'กรุณากรอกเหตุผล',
  absence_VALIDATION_START_DATE_NOT_FUTURE: 'วันที่เริ่มต้นต้องไม่เกินวันนี้',
  absence_VALIDATION_START_DATE_NOT_PAST: 'วันที่เริ่มต้นต้องเป็นวันนี้หรือวันถัดไป',
  absence_WAITING_TITLE: 'รออนุมัติ',

  // absence - type labels
  absence_HAJJ_TITLE: 'ลาฮัจย์',

  // absence - tab labels
  absence_TAB_APPEAL: 'ยื่นลา',
  absence_TAB_WAITING: 'รออนุมัติ',
  absence_TAB_STATS: 'สถิติกาลา',
  absence_TAB_HISTORY: 'ประวัติการลา',

  // absence - Choose Absence (index tab)
  absence_CHOOSE_TITLE: 'เลือกประเภทการลา',
  absence_CHOOSE_SUBTITLE: 'เพื่อยื่นคำขอการลา กรุณาเลือกประเภทการลาที่ต้องการ',
  absence_SICK_DESCRIPTION: 'ยื่นคำขอลาป่วย',
  absence_BUSINESS_DESCRIPTION: 'ยื่นคำขอลากิจส่วนตัว',
  absence_RELAX_DESCRIPTION: 'ยื่นคำขอลาพักผ่อน',
  absence_BIRTH_DESCRIPTION: 'ยื่นคำขอลาคลอด',
  absence_POLICY_NOTE_LABEL: 'นโยบายการลา',
  absence_POLICY_NOTE_TEXT: 'การยื่นลาป่วยและลากิจส่วนตัวต้องรวมกันไม่เกิน 18 ครั้งและไม่เกิน 45 วันต่อปีงบประมาณ ลาพักผ่อนต้องรวมกันไม่เกิน 30 วันต่อปีงบประมาณ',

  // absence - Pending tab
  absence_PENDING_TITLE: 'รออนุมัติ',
  absence_PENDING_SUBTITLE: 'ติดตามสถานะของคำขอการลาที่ส่งแล้ว',
  absence_PENDING_BADGE: 'รออนุมัติ',
  absence_PENDING_STEP_DEPT_HEAD: 'กำลังรอการอนุมัติจากหัวหน้าแผนก',
  absence_PENDING_STEP_HR: 'กำลังรอการอนุมัติจากฝ่ายทรัพยากรบุคคล',

  // absence - Stats tab
  absence_STATS_LOADING_TITLE: 'กำลังโหลดสถิติ',
  absence_STATS_TITLE: 'สถิติการลา',
  absence_STATS_SUBTITLE: 'แสดงสถิติการลาของคุณในรอบปีงบประมาณปัจจุบัน',
  absence_STATS_NO_DATA: 'ยังไม่มีข้อมูล',
  absence_STATS_WORK_AGE_LABEL: 'อายุงาน',
  absence_STATS_WORK_AGE_UNIT: 'ปี',
  absence_STATS_CYCLE_DATE_LABEL: 'รอบปีงบประมาณ',
  absence_STATS_ALL_ABSENCES: 'การลาทั้งหมด',
  absence_STATS_USAGE_OVERVIEW: 'แสดงจำนวนวันและครั้งที่คุณลาป่วยและลากิจส่วนตัวในรอบปีงบประมาณปัจจุบัน',
  absence_STATS_OCCURRENCES: 'จำนวนครั้งที่ลา',
  absence_STATS_TOTAL_DAYS_LABEL: 'จำนวนวันที่ลา',
  absence_STATS_VACATION_ANNUAL: 'แสดงจำนวนวันลาพักผ่อนที่คุณใช้ไปและเหลืออยู่ในรอบปีงบประมาณปัจจุบัน',
  absence_STATS_USED_THIS_YEAR: 'จำนวนวันลาที่ใช้ / จำนวนวันลาที่เหลือ',
  absence_STATS_DAYS_FROM_PREV_YEAR: 'จำนวนวันลาพักผ่อนที่ยกมาจากปีที่แล้ว',
  absence_STATS_TOTAL_DAYS_THIS_YEAR: 'จำนวนวันลาพักผ่อนทั้งหมด',
  absence_STATS_MAX_ACCUMULATION: 'จำนวนวันลาพักผ่อนสูงสุดที่สามารถสะสมได้',
  absence_STATS_LATE_TITLE: 'มาสาย',
  absence_STATS_UNIT_TIMES: 'ครั้ง',
  absence_STATS_UNIT_DAYS: 'วัน',

  // absence - History tab
  absence_HISTORY_SUBTITLE: 'แสดงประวัติการลาทั้งหมดของคุณ',
  absence_HISTORY_DATE_PREFIX: 'วันที่ลา: ',

  // Meeting
  MEETING_HEADER_TITLE: 'การประชุม',
  MEETING_INCOMING: 'ประชุมเร็วๆ นี้',
  MEETING_LOADING_MEETINGS: 'กำลังโหลดข้อมูลการประชุม',
  MEETING_MENU_TITLE: 'การประชุม',
  MEETING_NO_HISTORY: 'ไม่มีประวัติการประชุม',
  MEETING_NO_INCOMING_MEETINGS: 'ไม่มีการประชุมเร็วๆ นี้',
  MEETING_NO_MEETINGS_TODAY: 'ไม่มีการประชุมวันนี้',
  MEETING_TODAY: 'ประชุมวันนี้',
  MEETING_UNABLE_TO_LOAD_MEETINGS: 'ไม่สามารถโหลดข้อมูลการประชุมได้',
  MEETING_AGENDA_TITLE: 'วาระการประชุม',
  MEETING_AGENDA_SECTION: 'วาระการประชุม',
  MEETING_TOPICS_COUNT: ' วาระ',
  MEETING_LOADING_AGENDA: 'กำลังโหลดวาระการประชุม',
  MEETING_NO_AGENDA: 'ไม่มีวาระการประชุม',
  MEETING_UNABLE_TO_LOAD_AGENDA: 'ไม่สามารถโหลดวาระการประชุมได้',

  // Public Repair
  PUBLIC_REPAIR_MENU_TITLE: 'แจ้งซ่อมสาธารณะ',
  PUBLIC_REPAIR_TITLE: 'แจ้งซ่อมสาธารณูปการ',

  PR_ROLE_INFORMER: 'ผู้แจ้งซ่อม',
  PR_ROLE_APPROVE: 'หัวหน้าสาธารณูปการ',
  PR_ROLE_ADMIN: 'เจ้าหน้าที่ธุรการ',
  PR_ROLE_HEADER: 'หัวหน้างาน',
  PR_ROLE_TECHNICIAN: 'ช่างเทคนิค',

  PR_TAB_INFORM: 'แจ้งซ่อม',
  PR_TAB_CURRENT: 'งานปัจจุบัน',
  PR_TAB_HISTORY: 'ประวัติ',
  PR_TAB_PENDING: 'รออนุมัติ',
  PR_TAB_ALL: 'ทั้งหมด',
  PR_TAB_APPROVED: 'อนุมัติแล้ว',
  PR_TAB_IN_PROGRESS: 'ดำเนินการ',
  PR_TAB_DONE: 'เสร็จสิ้น',
  PR_TAB_ASSIGNED: 'งานที่ได้รับ',

  PR_LOADING: 'กำลังโหลดรายการ',
  PR_LOADING_PRIVILEGE: 'กำลังตรวจสอบสิทธิ์',
  PR_NO_ITEMS: 'ไม่มีรายการแจ้งซ่อม',
  PR_ERROR_LOAD: 'ไม่สามารถโหลดรายการแจ้งซ่อมได้',
  PR_SELECT_ROLE: 'เลือกบทบาท',

  PR_FORM_WORK_CATEGORY: 'ประเภทงาน *',
  PR_FORM_PLACE: 'สถานที่ *',
  PR_FORM_DETAIL: 'รายละเอียดปัญหา *',
  PR_FORM_WORK_TYPE: 'ประเภทการซ่อม',
  PR_FORM_PHONE: 'เบอร์โทรศัพท์',
  PR_FORM_BUILDING: 'อาคาร',
  PR_FORM_REMARK: 'หมายเหตุ',
  PR_FORM_SUBMIT: 'ส่งคำขอแจ้งซ่อม',
  PR_FORM_SUCCESS: 'ส่งคำขอแจ้งซ่อมสำเร็จ',
  PR_FORM_ERROR: 'ไม่สามารถส่งคำขอแจ้งซ่อมได้',
  PR_FORM_REQUIRED: 'กรุณากรอกข้อมูลที่จำเป็น',
  PR_FORM_SELECT_CATEGORY: 'เลือกประเภทงาน',
  PR_FORM_SELECT_BUILDING: 'เลือกอาคาร',
  PR_FORM_SELECT_WORK_TYPE: 'เลือกประเภทการซ่อม',

  PR_DETAIL_TITLE: 'รายละเอียดการแจ้งซ่อม',
  PR_DETAIL_NUMBER: 'เลขที่',
  PR_DETAIL_CATEGORY: 'ประเภทงาน',
  PR_DETAIL_PLACE: 'สถานที่',
  PR_DETAIL_BUILDING: 'อาคาร',
  PR_DETAIL_STATUS: 'สถานะ',
  PR_DETAIL_INFORMER: 'ผู้แจ้ง',
  PR_DETAIL_DATE: 'วันที่แจ้ง',
  PR_DETAIL_DESCRIPTION: 'รายละเอียด',
  PR_DETAIL_TECHNICIANS: 'ช่างเทคนิค',
  PR_DETAIL_WORK_DATE: 'วันที่ดำเนินการ',
  PR_DETAIL_WORK_RESULT: 'ผลการดำเนินการ',
  PR_DETAIL_PROBLEM: 'ปัญหาที่พบ',
  PR_DETAIL_MATERIALS: 'วัสดุที่ขอเบิก',

  PR_ACTION_APPROVE: 'อนุมัติ',
  PR_ACTION_REJECT: 'ไม่อนุมัติ',
  PR_ACTION_ACCEPT: 'ออกเลขรับ',
  PR_ACTION_EXAMINE_OK: 'งานเรียบร้อย',
  PR_ACTION_EXAMINE_NOT_OK: 'งานไม่เรียบร้อย',

  // Repair Computer
  REPAIR_COMPUTER_APPROVEMENT: 'อนุมัติครุภัณฑ์คอมพิวเตอร์',
  REPAIR_COMPUTER_APPROVEMENT_DESCRIPTION: 'อนุมัติผลลัพธ์งานซ่อมคอมพิวเตอร์',
  REPAIR_COMPUTER_ASSIGN_CONFIRM: 'ยืนยันการมอบหมาย',
  REPAIR_COMPUTER_BACK_TO_CURRENT_JOB: 'กลับไปยังงานปัจจุบัน',
  REPAIR_COMPUTER_CANNOT_INFORM_JOB: 'ไม่สามารถแจ้งงานได้',
  REPAIR_COMPUTER_CHECKING_PRIVILEGE: 'กำลังตรวจสอบสิทธิ์',
  REPAIR_COMPUTER_CHECKING_REQUEST: 'กำลังตรวจสอบคำขอ',
  REPAIR_COMPUTER_CURRENT_JOB: 'งานปัจจุบัน',
  REPAIR_COMPUTER_CURRENT_JOBS_DESCRIPTION: 'ติดตามคำขอบริการที่ใช้งานอยู่และการบำรุงรักษาที่กำลังดำเนินการ',
  REPAIR_COMPUTER_DELETE_CONFIRM_MESSAGE: 'คุณต้องการลบงานซ่อมคอมพิวเตอร์นี้ใช่หรือไม่?',
  REPAIR_COMPUTER_DETAIL: 'รายละเอียด',
  REPAIR_COMPUTER_DETAIL_LABEL: 'รายละเอียด:',
  REPAIR_COMPUTER_EDIT_JOB: 'แก้ไขงาน',
  REPAIR_COMPUTER_FOREMAN: 'หัวหน้าช่าง',
  REPAIR_COMPUTER_INFORM: 'แจ้ง',
  REPAIR_COMPUTER_INFORM_DATE_LABEL: 'วันที่แจ้ง:',
  REPAIR_COMPUTER_JOB_DELETED_SUCCESS_MESSAGE: 'ลบงานซ่อมสำเร็จ',
  REPAIR_COMPUTER_JOB_DETAIL: 'รายละเอียดงาน',
  REPAIR_COMPUTER_JOB_ID_LABEL: 'รหัสงาน:',
  REPAIR_COMPUTER_JOB_UPDATED_SUCCESS_MESSAGE: 'อัปเดตงานซ่อมคอมพิวเตอร์สำเร็จ',
  REPAIR_COMPUTER_JOBS: 'งาน',
  REPAIR_COMPUTER_LOADING_CURRENT_JOBS: 'กำลังโหลดงานปัจจุบัน',
  REPAIR_COMPUTER_LOADING_DETAIL: 'กำลังโหลดรายละเอียด',
  REPAIR_COMPUTER_LOADING_JOB_DETAIL: 'กำลังโหลดรายละเอียดงาน',
  REPAIR_COMPUTER_LOADING_MANAGE_JOBS: 'กำลังโหลดงานที่จัดการ',
  REPAIR_COMPUTER_LOADING_NEW_JOBS: 'กำลังโหลดงานใหม่',
  REPAIR_COMPUTER_LOADING_QUEUE: 'กำลังโหลดคิว',
  REPAIR_COMPUTER_MANAGE_JOB: 'จัดการงาน',
  REPAIR_COMPUTER_MENU_TITLE: 'แจ้งซ่อมคอมพิวเตอร์',
  REPAIR_COMPUTER_NEW_JOB: 'งานใหม่',
  REPAIR_COMPUTER_NO_CURRENT_JOBS: 'ไม่มีงานปัจจุบัน',
  REPAIR_COMPUTER_NO_JOBS_TO_MANAGE: 'ไม่มีงานที่ต้องจัดการ',
  REPAIR_COMPUTER_NO_NEW_JOBS: 'ไม่มีงานใหม่',
  REPAIR_COMPUTER_NO_WORKER_QUEUE: 'ไม่มีคิวช่าง',
  REPAIR_COMPUTER_PENDING_JOB_TYPE: 'รอการระบุประเภทงาน',
  REPAIR_COMPUTER_PHONE: 'โทรศัพท์',
  REPAIR_COMPUTER_PHONE_LABEL: 'โทรศัพท์:',
  REPAIR_COMPUTER_QUEUE: 'คิว',
  REPAIR_COMPUTER_REJECT_DETAIL_LABEL: 'รายละเอียดการปฏิเสธ:',
  REPAIR_COMPUTER_REQUEST_SUBMITTED_SUCCESS_MESSAGE: 'ส่งคำขอแจ้งซ่อมคอมพิวเตอร์สำเร็จ',
  REPAIR_COMPUTER_SELECT_ROLE: 'เลือกบทบาท',
  REPAIR_COMPUTER_STATUS_LABEL: 'สถานะ:',
  REPAIR_COMPUTER_SUPPLY_CODE: 'รหัสครุภัณฑ์',
  REPAIR_COMPUTER_SUPPLY_CODE_LABEL: 'รหัสครุภัณฑ์:',
  REPAIR_COMPUTER_REPAIR_TYPE_LABEL: 'ประเภทงาน:',
  REPAIR_COMPUTER_TITLE: 'ซ่อมคอมพิวเตอร์',
  REPAIR_COMPUTER_UNABLE_TO_DELETE_JOB: 'ไม่สามารถลบงานซ่อมได้',
  REPAIR_COMPUTER_UNABLE_TO_LOAD_CURRENT_JOBS: 'ไม่สามารถโหลดงานปัจจุบันได้',
  REPAIR_COMPUTER_UNABLE_TO_LOAD_JOB_DETAIL: 'ไม่สามารถโหลดรายละเอียดงานได้',
  REPAIR_COMPUTER_UNABLE_TO_LOAD_MANAGE_JOBS: 'ไม่สามารถโหลดงานที่จัดการได้',
  REPAIR_COMPUTER_UNABLE_TO_LOAD_NEW_JOBS: 'ไม่สามารถโหลดงานใหม่ได้',
  REPAIR_COMPUTER_UNABLE_TO_LOAD_WORKER_QUEUE: 'ไม่สามารถโหลดคิวช่างได้',
  REPAIR_COMPUTER_UNABLE_TO_OPEN_JOB_DETAIL: 'ไม่สามารถเปิดรายละเอียดงานได้',
  REPAIR_COMPUTER_UNABLE_TO_SUBMIT_REQUEST: 'ไม่สามารถส่งคำขอแจ้งซ่อมคอมพิวเตอร์ได้',
  REPAIR_COMPUTER_UNABLE_TO_UPDATE_JOB: 'ไม่สามารถอัปเดตงานซ่อมคอมพิวเตอร์ได้',
  REPAIR_COMPUTER_UPDATE_CONFIRM_MESSAGE: 'คุณต้องการอัปเดตข้อมูลงานซ่อมคอมพิวเตอร์ใช่หรือไม่?',
  REPAIR_COMPUTER_UPDATE_CONFIRM_TITLE: 'ยืนยันการอัปเดต',
  REPAIR_COMPUTER_USER_LABEL: 'ผู้ใช้:',
  REPAIR_COMPUTER_WORKER: 'ช่าง',
  REPAIR_COMPUTER_WORKER_LABEL: 'ช่าง:',
  REPAIR_COMPUTER_VIEW_NEW_WORKER_JOBS_DESCRIPTION: 'ดูงานซ่อมคอมพิวเตอร์ใหม่ที่มอบหมายให้ช่าง',
  REPAIR_COMPUTER_VIEW_WORKER_CURRENT_JOBS_DESCRIPTION: 'ดูงานของช่างที่กำลังดำเนินการอยู่',
  REPAIR_COMPUTER_VIEW_WORKER_HISTORY_DESCRIPTION: 'ดูประวัติงานซ่อมคอมพิวเตอร์ของช่าง',
  REPAIR_COMPUTER_VIEW_FOREMAN_NEW_JOBS_DESCRIPTION: 'ดูงานซ่อมคอมพิวเตอร์ใหม่ที่รอการจัดการ',
  REPAIR_COMPUTER_VIEW_FOREMAN_HISTORY_DESCRIPTION: 'ดูประวัติงานซ่อมคอมพิวเตอร์ของหัวหน้าช่าง',
  REPAIR_COMPUTER_CODE_NOT_AVAILABLE: 'ไม่ระบุ',
  REPAIR_COMPUTER_NEW_REQUEST: 'คำขอซ่อมใหม่',
  REPAIR_COMPUTER_NEW_REQUEST_DESCRIPTION: 'กรุณาให้รายละเอียดเกี่ยวกับปัญหาคอมพิวเตอร์',
  REPAIR_COMPUTER_OPTIONAL: '(ไม่บังคับ)',
  REPAIR_COMPUTER_SUBMIT_REQUEST: 'ส่งคำขอ',
  REPAIR_COMPUTER_REPAIR_HISTORY: 'ประวัติการซ่อม',
  REPAIR_COMPUTER_REPAIR_HISTORY_DESCRIPTION: 'ติดตามคำขอบริการที่เสร็จสมบูรณ์และบันทึกการบำรุงรักษา',
  REPAIR_COMPUTER_TECHNICIAN_QUEUE: 'คิวช่างซ่อม',
  REPAIR_COMPUTER_TECHNICIAN_QUEUE_DESCRIPTION: 'ติดตามงานที่มอบหมายและปริมาณงานของช่าง',
  REPAIR_COMPUTER_TOTAL_JOBS: 'งานทั้งหมด',
  REPAIR_COMPUTER_ACTIVE_LABEL: 'Active',
  REPAIR_COMPUTER_ACTIVE_JOBS_PREFIX: 'Active Jobs: ',

  // Calendar
  CALENDAR_DESCRIPTION: 'หน้านี้คือหน้าปฏิทิน',
  CALENDAR_TITLE: 'ปฏิทิน',

  // Person Search
  PERSON_SEARCH_DESCRIPTION: 'หน้านี้คือหน้าค้นหาบุคลากร',
  PERSON_SEARCH_TITLE: 'ค้นหาบุคลากร',

  // Examiner / Examinar
  EXAMINER_MENU_TITLE: 'ตารางคุมสอบ',
  EXAMINAR_HEADER_TITLE: 'ตารางคุมสอบ',
  EXAMINAR_DETAIL_HEADER_TITLE: 'รายละเอียดการสอบ',
  EXAMINAR_FILTER_YEAR: 'ปีการศึกษา',
  EXAMINAR_FILTER_TERM: 'ภาคการศึกษา',
  EXAMINAR_FILTER_PERIOD: 'ช่วงการสอบ',
  EXAMINAR_UPCOMING_LABEL: 'ตารางคุมสอบที่กำลังมาถึง',
  EXAMINAR_VIEW_DETAILS: 'ดูรายละเอียด',
  EXAMINAR_VENUE_LABEL: 'สถานที่สอบ',
  EXAMINAR_SUBJECT_LIST_HEADING: 'รายวิชาสอบ',
  EXAMINAR_PARTNERS_HEADING: 'ผู้คุมสอบ',
  EXAMINAR_LOADING: 'กำลังโหลดตารางคุมสอบ...',
  EXAMINAR_NO_EXAMS: 'ไม่พบตารางคุมสอบ',
  EXAMINAR_UNABLE_TO_LOAD: 'ไม่สามารถโหลดข้อมูลตารางคุมสอบได้',
  EXAMINAR_TERM_1: 'ภาคการศึกษาที่ 1',
  EXAMINAR_TERM_2: 'ภาคการศึกษาที่ 2',
  EXAMINAR_TERM_SUMMER: 'ภาคฤดูร้อน',
  EXAMINAR_PERIOD_MIDTERM: 'กลางภาค',
  EXAMINAR_PERIOD_FINAL: 'ปลายภาค',
  EXAMINAR_PERIOD_MIDTERM_FULL: 'การสอบกลางภาค',
  EXAMINAR_PERIOD_FINAL_FULL: 'การสอบปลายภาค',
  EXAMINAR_STATUS_PAST: 'ผ่านไปแล้ว',
  EXAMINAR_STATUS_TODAY: 'วันนี้',
  EXAMINAR_STATUS_INCOMING: 'กำลังมาถึง',
  EXAMINAR_SUBJECT_ID_PREFIX: 'รหัส: ',
  EXAMINAR_STUDENTS_SUFFIX: ' นักศึกษา',
  EXAMINAR_SECTION_PREFIX: 'ตอน: ',
  EXAMINAR_SUBJECTS_COUNT: ' วิชา',
  EXAMINAR_STAFF_COUNT: ' คน',
  EXAMINAR_NO_SUBJECTS: 'ไม่มีรายวิชา',
  EXAMINAR_NO_STAFF: 'ไม่มีรายชื่อผู้คุมสอบ',
  EXAMINAR_DURATION_HOUR: 'ชม.',
  EXAMINAR_DURATION_MINUTE: 'น.',

  // Forgot Timestamp
  FORGOT_TIMESTAMP_DESCRIPTION: 'หน้านี้คือหน้าลืมลงเวลา',
  FORGOT_TIMESTAMP_TITLE: 'ลืมลงเวลา',

  // Forgot Timestamp - common
  FORGOT_TIMESTAMP_STAMP_IN: 'ลืมลงเวลาเข้า',
  FORGOT_TIMESTAMP_STAMP_OUT: 'ลืมลงเวลาออก',
  FORGOT_TIMESTAMP_ACTION_REQUIRED: 'ต้องดำเนินการ',
  FORGOT_TIMESTAMP_APPROVED_BADGE: 'อนุมัติแล้ว',
  FORGOT_TIMESTAMP_REJECTED_BADGE: 'ปฏิเสธแล้ว',
  FORGOT_TIMESTAMP_REASON_LABEL: 'เหตุผลการแก้ไข',

  // Forgot Timestamp - index screen
  FORGOT_TIMESTAMP_APPEAL_DOCUMENT: 'กรุณาไปที่พอร์ทัล HR เพื่อยื่นอุทธรณ์พร้อมเอกสารประกอบ',
  FORGOT_TIMESTAMP_NOTE_TEXT: 'หากคุณลืมลงเวลาเข้างานหรือออกงาน คุณสามารถกรอกแบบฟอร์มคำขอลืมลงเวลาภายใน 3 วันหลังจากวันที่ลืมลงเวลาได้ที่หน้านี้',
  FORGOT_TIMESTAMP_COMPANY_CYCLE_LABEL: 'รอบบริษัท',

  // Forgot Timestamp - detail screen
  FORGOT_TIMESTAMP_CONTEXT_IN_TITLE: 'ลืมลงเวลาเข้างาน?',
  FORGOT_TIMESTAMP_CONTEXT_OUT_TITLE: 'ลืมลงเวลาออกงาน?',
  FORGOT_TIMESTAMP_CONTEXT_IN_DESC: 'เลือกเวลาที่ถูกต้องที่คุณลงเวลาเข้างานในวันนั้น',
  FORGOT_TIMESTAMP_CONTEXT_OUT_DESC: 'เลือกเวลาที่ถูกต้องที่คุณลงเวลาออกงานในวันนั้น',
  FORGOT_TIMESTAMP_CONTEXT_DEFAULT_DESC: 'กรอกแบบฟอร์มด้านล่างเพื่อส่งคำขอลืมลงเวลา',
  FORGOT_TIMESTAMP_FIELD_APPROVER: 'ผู้อนุมัติ',
  FORGOT_TIMESTAMP_SELECT_APPROVER: 'เลือกผู้อนุมัติ',
  FORGOT_TIMESTAMP_FIELD_EMPLOYEE_NAME: 'ชื่อพนักงาน',
  FORGOT_TIMESTAMP_FIELD_ORIGINAL_DATE: 'วันที่เดิม',
  FORGOT_TIMESTAMP_FIELD_CORRECTED_TIME: 'เวลาที่แก้ไข',
  FORGOT_TIMESTAMP_HOUR: 'ชั่วโมง',
  FORGOT_TIMESTAMP_MINUTE: 'นาที',
  FORGOT_TIMESTAMP_SELECT_TIME: 'เลือกเวลา',
  FORGOT_TIMESTAMP_DONE: 'เสร็จสิ้น',
  FORGOT_TIMESTAMP_IN_HINT: 'เวลาเริ่มงาน 07:00 - 08:45 น.',
  FORGOT_TIMESTAMP_OUT_HINT: 'เวลาเลิกงาน 16:30 - 20:30 น.',
  FORGOT_TIMESTAMP_GUIDANCE_NOTE: 'คำขอต้องส่งภายในวันศุกร์ เวลา 17:00 น. เพื่อให้ทันรอบเงินเดือน',
  FORGOT_TIMESTAMP_REASON_PLACEHOLDER: 'กรอกเหตุผล',
  FORGOT_TIMESTAMP_APPROVER_REQUIRED: 'กรุณาเลือกผู้อนุมัติ',
  FORGOT_TIMESTAMP_TIME_REQUIRED: 'กรุณาเลือกเวลา',
  FORGOT_TIMESTAMP_REASON_REQUIRED: 'กรุณากรอกเหตุผล',
  FORGOT_TIMESTAMP_SUBMIT: 'ส่งคำขอ',
  FORGOT_TIMESTAMP_SUBMITTING: 'กำลังส่ง...',
  FORGOT_TIMESTAMP_REMOVING: 'กำลังลบ...',
  FORGOT_TIMESTAMP_APPROVER_LIST_TITLE: 'รายชื่อผู้อนุมัติ',
  FORGOT_TIMESTAMP_CONFIRM_SUBMIT_TITLE: 'ยืนยันการส่งคำขอ',
  FORGOT_TIMESTAMP_CONFIRM_SUBMIT_MESSAGE: 'คุณต้องการส่งคำขอลืมลงเวลานี้ใช่หรือไม่?',
  FORGOT_TIMESTAMP_CONFIRM_REMOVE_TITLE: 'ยืนยันการลบ',
  FORGOT_TIMESTAMP_CONFIRM_REMOVE_MESSAGE: 'คุณต้องการลบคำขอลืมลงเวลานี้ใช่หรือไม่?',

  // Forgot Timestamp - history screen
  FORGOT_TIMESTAMP_HISTORY_SUBTITLE: 'ดูคำขอลงเวลาที่ดำเนินการเสร็จสิ้นแล้ว',
  FORGOT_TIMESTAMP_TOTAL_APPROVED: 'อนุมัติทั้งหมด',
  FORGOT_TIMESTAMP_TOTAL_REJECTED: 'ปฏิเสธทั้งหมด',
  FORGOT_TIMESTAMP_END_OF_HISTORY: 'สิ้นสุดประวัติ',

  // Forgot Timestamp - history detail screen
  FORGOT_TIMESTAMP_DETAIL_TITLE: 'รายละเอียดการลงเวลา',
  FORGOT_TIMESTAMP_TYPE_LABEL: 'ประเภท',
  FORGOT_TIMESTAMP_STAMP_IN_TYPE: 'ลงเวลาเข้า',
  FORGOT_TIMESTAMP_STAMP_OUT_TYPE: 'ลงเวลาออก',
  FORGOT_TIMESTAMP_APPEAL_DATE: 'วันที่ยื่น',
  FORGOT_TIMESTAMP_TIMESTAMP_DATETIME: 'วันและเวลาลงเวลา',
  FORGOT_TIMESTAMP_TIMESTAMP_TYPE: 'ประเภทการลงเวลา',

  // Modal
  MODAL_TITLE: 'หน้าต่างโมดัล',
} as const;
