export const TEXT = {
  // Shared
  CANCEL: 'ยกเลิก',
  CLOSE: 'ปิด',
  CONFIRM_DELETE: 'ยืนยันการลบ',
  DELETE: 'ลบ',
  DATE_PICKER_NEXT_MONTH_LABEL: '>',
  DATE_PICKER_PREVIOUS_MONTH_LABEL: '<',
  NAV_HOME_ACCESSIBILITY_LABEL: 'ไปหน้าหลัก',
  SHARED_ADD_THAI: 'เพิ่ม',
  SHARED_BACK_THAI: 'ย้อนกลับ',
  SHARED_BACK_TO_HOME_THAI: 'กลับหน้าหลัก',
  SHARED_CLOSE_THAI: 'ปิด',
  SHARED_DELETE_THAI: 'ลบ',
  SHARED_DEPARTMENT_LABEL: 'แผนก:',
  SHARED_EMPTY_DATA: 'ไม่มีข้อมูล',
  SHARED_ERROR_TITLE_THAI: 'เกิดข้อผิดพลาด',
  SHARED_HISTORY: 'ประวัติ',
  SHARED_LOADING_DATA_TITLE: 'กำลังโหลดข้อมูล',
  SHARED_LOADING_DESCRIPTION: 'กรุณารอสักครู่',
  SHARED_LOADING_HISTORY: 'กำลังโหลดประวัติ',
  SHARED_MODAL: 'โมดัล',
  SHARED_NO_HISTORY: 'ไม่มีประวัติ',
  SHARED_NO_ITEMS: 'ไม่มีรายการ',
  SHARED_GO_BACK: 'ย้อนกลับ',
  SHARED_OK: 'ตกลง',
  SHARED_PLEASE_WAIT_A_MOMENT: 'กรุณารอสักครู่',
  SHARED_REQUIRED_INFORMATION: 'ข้อมูลที่จำเป็น',
  SHARED_RETRY: 'ลองใหม่',
  SHARED_RETRY_THAI: 'ลองใหม่',
  SHARED_SEARCH_NAME_PLACEHOLDER: 'ค้นหาชื่อ',
  SHARED_SOMETHING_WENT_WRONG: 'เกิดข้อผิดพลาด',
  SHARED_SUCCESS: 'สำเร็จ',
  SHARED_UNABLE_TO_COMPLETE: 'ไม่สามารถดำเนินการได้',
  SHARED_UNABLE_TO_LOAD_HISTORY: 'ไม่สามารถโหลดประวัติได้',
  SHARED_UPDATE: 'อัปเดต',
  SHARED_UPDATING: 'กำลังอัปเดต...',

  // Home
  HOME_APP_NAME: 'Intania',
  HOME_CONFIRM_LOGOUT_TITLE: 'ยืนยันการออกจากระบบ',
  HOME_CONFIRM_LOGOUT_MESSAGE: 'คุณต้องการออกจากระบบนี้ใช่หรือไม่?',
  HOME_GREETING_MORNING: 'สวัสดีตอนเช้า',
  HOME_GREETING_AFTERNOON: 'สวัสดีตอนบ่าย',
  HOME_GREETING_EVENING: 'สวัสดีตอนเย็น',
  HOME_LOADING_NEWS_TITLE: 'กำลังโหลดข่าวสาร',
  HOME_LOGOUT: 'ออกจากระบบ',
  HOME_MENU_SECTION_DESCRIPTION: 'เลือกเมนูที่ต้องการใช้งาน',
  HOME_MENU_SECTION_TITLE: 'เมนู',
  HOME_NEWS_SECTION_TITLE: 'ข่าวบุคลากร',
  HOME_NEWS_SECTION_SUBTITLE: 'ข่าวสารและประกาศล่าสุด',
  HOME_NO_NEWS_MESSAGE: 'ไม่พบข่าวสาร',
  HOME_SEE_ALL_THAI: 'ดูทั้งหมด',
  HOME_SIGNING_OUT_TITLE: 'กำลังออกจากระบบ',
  HOME_TITLE: 'หน้าหลัก',
  PROFILE_TITLE: 'โปรไฟล์',
  PROFILE_SUBTITLE: 'ข้อมูลส่วนตัว',
  HOME_WELCOME_DESCRIPTION: 'ระบบสำหรับบุคลากรมหาวิทยาลัยสงขลานครินทร์',

  // Auth
  AUTH_LOGIN: 'เข้าสู่ระบบ',
  AUTH_LOGIN_FAILED: 'เข้าสู่ระบบไม่สำเร็จ',
  AUTH_SIGNING_IN_TITLE: 'กำลังเข้าสู่ระบบ',

  // absence
  ABSENCE_APPROVER_LABEL: 'ผู้อนุมัติ',
  ABSENCE_REQUESTER_LABEL: 'ผู้ยื่นคำขอ',
  ABSENCE_APPROVER_PLACEHOLDER: 'เลือกผู้อนุมัติ',
  ABSENCE_BIRTH_TITLE: 'ลาคลอด',
  ABSENCE_BUSINESS_FORM_TITLE: 'แบบฟอร์มไปราชการ',
  ABSENCE_BUSINESS_SUBMIT_SUCCESS_MESSAGE: 'ส่งคำขอลากิจส่วนตัวสำเร็จ',
  ABSENCE_BUSINESS_TITLE: 'ลากิจส่วนตัว',
  ABSENCE_BIRTH_SUBMIT_SUCCESS_MESSAGE: 'ส่งคำขอลาคลอดสำเร็จ',
  ABSENCE_CANNOT_REQUEST_TITLE: 'ไม่สามารถทำเรื่องลาได้',
  ABSENCE_CONFIRM_REMOVE_MESSAGE: 'กรุณายืนยันก่อนลบคำขอการลานี้',
  ABSENCE_CONFIRM_REMOVE_TITLE: 'ยืนยันการลบคำขอ',
  ABSENCE_CONFIRM_SUBMIT_ACTION: 'ยืนยัน',
  ABSENCE_CONFIRM_SUBMIT_CANCEL: 'ยกเลิก',
  ABSENCE_CONFIRM_SUBMIT_MESSAGE: 'กรุณายืนยันก่อนส่งคำขอการลานี้',
  ABSENCE_CONFIRM_SUBMIT_TITLE: 'ยืนยันคำขอการลา',
  ABSENCE_CONTACT_CHANNEL_LABEL: 'ช่องทางติดต่อ',
  ABSENCE_CONTACT_CHANNEL_PLACEHOLDER: 'กรอกช่องทางติดต่อ',
  ABSENCE_DAY_UNIT: 'วัน',
  ABSENCE_DELEGATE_LABEL: 'ผู้รับมอบหมาย',
  ABSENCE_DELEGATE_PLACEHOLDER: 'เลือกผู้รับมอบหมาย',
  ABSENCE_END_DATE_LABEL: 'วันที่สิ้นสุด',
  ABSENCE_HALF_DAY_FIRST_AFTERNOON: 'วันแรกครึ่งวันบ่าย',
  ABSENCE_HALF_DAY_FIRST_AFTERNOON_LAST_MORNING: 'วันแรกครึ่งวันบ่าย - วันสุดท้ายครึ่งวันเช้า',
  ABSENCE_HALF_DAY_FIRST_MORNING: 'วันแรกครึ่งวันเช้า',
  ABSENCE_HALF_DAY_LABEL: 'ลาครึ่งวัน',
  ABSENCE_HALF_DAY_LAST_MORNING: 'วันสุดท้ายครึ่งวันเช้า',
  ABSENCE_HALF_DAY_NONE: '-',
  ABSENCE_HALF_DAY_PLACEHOLDER: 'เลือกตัวเลือกลาครึ่งวัน',
  ABSENCE_HISTORY_TAB_TITLE: 'ประวัติ',
  ABSENCE_HISTORY_TITLE: 'แสดงประวัติการลา',
  ABSENCE_INIT_LOAD_ERROR_MESSAGE: 'ไม่สามารถโหลดข้อมูลตั้งต้นได้',
  ABSENCE_INITIAL_DATA_LOADED: 'โหลดข้อมูลตั้งต้นเรียบร้อยแล้ว',
  ABSENCE_INVALID_WEEKEND_DATE_MESSAGE: 'กรุณาเลือกวันจันทร์ถึงวันศุกร์',
  ABSENCE_INVALID_WEEKEND_DATE_TITLE: 'วันที่ไม่ถูกต้อง',
  ABSENCE_LEAVE_DATE_LABEL: 'วันที่ลา',
  ABSENCE_LEAVE_DAY_COUNT_LABEL: 'จำนวนวันลา',
  ABSENCE_DETAIL_SUBTITLE: 'รายละเอียดคำขอลา',
  ABSENCE_DETAIL_TITLE: 'รายละเอียดการลา',
  ABSENCE_DETAIL_INFO_SECTION: 'ข้อมูลการลา',
  ABSENCE_DETAIL_ATTACHMENT_SECTION: 'ไฟล์แนบ',
  ABSENCE_VIEW_ATTACHED_FILE: 'ดูไฟล์แนบ',
  ABSENCE_MEDICAL_CERTIFICATE_ACTION: 'เลือกไฟล์',
  ABSENCE_MEDICAL_CERTIFICATE_LABEL: 'ใบรับรองแพทย์',
  ABSENCE_MEDICAL_CERTIFICATE_TOGGLE: 'แนบใบรับรองแพทย์',
  ABSENCE_MEDICAL_CERTIFICATE_PLACEHOLDER: 'ยังไม่ได้เลือกไฟล์',
  ABSENCE_MEDICAL_CERTIFICATE_REMOVE: 'ลบไฟล์',
  ABSENCE_PERMISSION_REQUIRED_MESSAGE: 'ต้องการสิทธิ์ในการเข้าถึงคลังภาพของคุณ',
  ABSENCE_PERMISSION_REQUIRED_TITLE: 'ต้องการสิทธิ์',
  ABSENCE_REASON_LABEL: 'เหตุผล',
  ABSENCE_REASON_PLACEHOLDER: 'กรอกเหตุผล',
  ABSENCE_RELAX_FORM_TITLE: 'แบบฟอร์มลาพักผ่อน',
  ABSENCE_RELAX_SUBMIT_SUCCESS_MESSAGE: 'ส่งคำขอลาพักผ่อนสำเร็จ',
  ABSENCE_RELAX_TITLE: 'ลาพักผ่อน',
  ABSENCE_REQUEST_TYPE_PROMPT: 'เลือกประเภทการลา',
  ABSENCE_SELECT_DATE_HINT: 'เลือกวันที่เริ่มต้นและวันที่สิ้นสุด',
  ABSENCE_SICK_FORM_TITLE: 'แบบฟอร์มลาป่วย',
  ABSENCE_SICK_SUBMIT_ERROR_MESSAGE: 'ไม่สามารถส่งคำขอลาป่วยได้',
  ABSENCE_SICK_SUBMIT_SUCCESS_MESSAGE: 'ส่งคำขอลาป่วยสำเร็จ',
  ABSENCE_SICK_TITLE: 'ลาป่วย',
  ABSENCE_START_DATE_LABEL: 'วันที่เริ่มต้น',
  ABSENCE_SUBMIT_ERROR_MESSAGE: 'ไม่สามารถส่งคำขอการลาได้',
  ABSENCE_SUBMIT_REQUEST: 'ส่งคำขอ',
  ABSENCE_SUBMITTING_LABEL: 'กำลังส่งคำขอ...',
  ABSENCE_TITLE: 'การลา',
  ABSENCE_TRAVEL_DETAIL_LABEL: 'รายละเอียดการเดินทาง',
  ABSENCE_TRAVEL_DETAIL_PLACEHOLDER: 'กรอกรายละเอียดการเดินทาง',
  ABSENCE_VALIDATION_AGENT_REQUIRED: 'กรุณาเพิ่มผู้รับมอบหมายอย่างน้อย 1 คน',
  ABSENCE_VALIDATION_APPROVER_REQUIRED: 'กรุณาเลือกผู้อนุมัติ',
  ABSENCE_VALIDATION_CONTACT_REQUIRED: 'กรุณากรอกช่องทางติดต่อ',
  ABSENCE_VALIDATION_DATE_REQUIRED: 'กรุณาเลือกวันที่ลา',
  ABSENCE_VALIDATION_END_DATE_AFTER_START: 'วันที่สิ้นสุดต้องไม่ก่อนวันที่เริ่มต้น',
  ABSENCE_VALIDATION_END_DATE_NOT_FUTURE: 'วันที่สิ้นสุดต้องไม่เกินวันนี้',
  ABSENCE_VALIDATION_REASON_REQUIRED: 'กรุณากรอกเหตุผล',
  ABSENCE_VALIDATION_START_DATE_NOT_FUTURE: 'วันที่เริ่มต้นต้องไม่เกินวันนี้',
  ABSENCE_VALIDATION_START_DATE_NOT_PAST: 'วันที่เริ่มต้นต้องเป็นวันนี้หรือวันถัดไป',
  ABSENCE_WAITING_TITLE: 'รออนุมัติการลา',

  // absence - type labels
  ABSENCE_HAJJ_TITLE: 'ลาฮัจย์',

  // absence - tab labels
  ABSENCE_TAB_APPEAL: 'ยื่นลา',
  ABSENCE_TAB_WAITING: 'รออนุมัติ',
  ABSENCE_TAB_STATS: 'สถิติกาลา',
  ABSENCE_TAB_HISTORY: 'ประวัติการลา',
  // absence - boss bottom tabs + top tabs
  ABSENCE_MY_LEAVE_TAB: 'การลาของฉัน',
  ABSENCE_APPROVE_LEAVE_TAB: 'อนุมัติลา',
  ABSENCE_MY_LEAVE_PENDING_TAB: 'รออนุมัติ',
  ABSENCE_MY_LEAVE_HISTORY_TAB: 'ประวัติ',
  ABSENCE_APPROVE_PENDING_TAB: 'อนุมัติการลา',
  ABSENCE_APPROVE_HISTORY_TAB: 'ประวัติการอนุมัติ',
  ABSENCE_APPROVE_HISTORY_EMPTY: 'ไม่มีประวัติการอนุมัติ',
  ABSENCE_APPROVE_STATUS_APPROVED: 'อนุมัติแล้ว',
  ABSENCE_APPROVE_STATUS_REJECTED: 'ไม่อนุมัติ',

  // absence - Choose Absence (index tab)
  ABSENCE_CHOOSE_TITLE: 'เลือกประเภทการลา',
  ABSENCE_CHOOSE_SUBTITLE: 'เพื่อยื่นคำขอการลา กรุณาเลือกประเภทการลาที่ต้องการ',
  ABSENCE_SICK_DESCRIPTION: 'ยื่นคำขอลาป่วย',
  ABSENCE_BUSINESS_DESCRIPTION: 'ยื่นคำขอลากิจส่วนตัว',
  ABSENCE_RELAX_DESCRIPTION: 'ยื่นคำขอลาพักผ่อน',
  ABSENCE_BIRTH_DESCRIPTION: 'ยื่นคำขอลาคลอด',
  ABSENCE_POLICY_NOTE_LABEL: 'นโยบายการลา',
  ABSENCE_POLICY_NOTE_TEXT: 'การยื่นลาป่วยและลากิจส่วนตัวต้องรวมกันไม่เกิน 18 ครั้งและไม่เกิน 45 วันต่อปีงบประมาณ',

  // absence - Pending tab
  ABSENCE_PENDING_TITLE: 'รออนุมัติ',
  ABSENCE_PENDING_SUBTITLE: 'ติดตามสถานะของคำขอการลาที่ส่งแล้ว',
  ABSENCE_PENDING_BADGE: 'รออนุมัติ',
  ABSENCE_PENDING_STEP_DEPT_HEAD: 'กำลังรอการอนุมัติจากหัวหน้าแผนก',
  ABSENCE_PENDING_STEP_HR: 'กำลังรอการอนุมัติจากฝ่ายทรัพยากรบุคคล',
  ABSENCE_APPROVE_TAB: 'อนุมัติการลาของผู้อื่น',
  ABSENCE_MINE_TAB: 'อนุมัติการลาของฉัน',
  ABSENCE_APPROVE_EMPTY: 'ไม่มีคำขอลาที่รออนุมัติ',
  ABSENCE_APPROVE_SUBTITLE: 'คำขอลาที่รอให้คุณอนุมัติ',
  ABSENCE_MINE_SUBTITLE: 'คำขอลาของคุณที่รอการอนุมัติ',

  // absence - Approval detail / decision
  ABSENCE_APPROVE_DETAIL_SUBTITLE: 'พิจารณาคำขอลา',
  ABSENCE_APPROVE_REQUESTER_LABEL: 'ผู้ยื่นลา',
  ABSENCE_APPROVE_TYPE_LABEL: 'ประเภทการลา',
  ABSENCE_APPROVE_ACCEPT: 'อนุมัติ',
  ABSENCE_APPROVE_REJECT: 'ไม่อนุมัติ',
  ABSENCE_APPROVE_NOTE_LABEL: 'ความเห็น',
  ABSENCE_APPROVE_NOTE_PLACEHOLDER: 'กรอกความเห็น',
  ABSENCE_APPROVE_NOTE_REQUIRED: 'กรุณากรอกความเห็น',
  ABSENCE_APPROVE_SUBMIT: 'บันทึกผลการพิจารณา',
  ABSENCE_APPROVE_SUBMIT_SUCCESS: 'บันทึกผลการพิจารณาเรียบร้อย',
  ABSENCE_APPROVE_SUBMIT_ERROR: 'ไม่สามารถบันทึกผลการพิจารณาได้',
  ABSENCE_APPROVE_CONFIRM_TITLE: 'ยืนยันการบันทึก',
  ABSENCE_APPROVE_CONFIRM_MESSAGE: 'คุณต้องการบันทึกผลการพิจารณานี้ใช่หรือไม่?',
  ABSENCE_APPROVE_CONFIRM_ACTION: 'ยืนยัน',

  // absence - Stats tab
  ABSENCE_STATS_LOADING_TITLE: 'กำลังโหลดสถิติ',
  ABSENCE_STATS_TITLE: 'สถิติการลาในรอบงบประมาณปัจจุบัน',
  ABSENCE_STATS_SUBTITLE: 'แสดงสถิติการลาของคุณในรอบปีงบประมาณปัจจุบัน',
  ABSENCE_STATS_NO_DATA: 'ยังไม่มีข้อมูล',
  ABSENCE_STATS_GENERAL_SECTION: 'ข้อมูลทั่วไป',
  ABSENCE_STATS_WORK_AGE_LABEL: 'อายุงาน',
  ABSENCE_STATS_WORK_AGE_UNIT: 'ปี',
  ABSENCE_STATS_CYCLE_DATE_LABEL: 'รอบปีงบประมาณ',
  ABSENCE_STATS_ALL_ABSENCES: 'การลาทั้งหมด',
  ABSENCE_STATS_USAGE_OVERVIEW: 'แสดงจำนวนวันและครั้งที่คุณลาป่วยและลากิจส่วนตัวในรอบปีงบประมาณปัจจุบัน',
  ABSENCE_STATS_OCCURRENCES: 'จำนวนครั้งที่ลา',
  ABSENCE_STATS_TOTAL_DAYS_LABEL: 'จำนวนวันที่ลา',
  ABSENCE_STATS_VACATION_ANNUAL: 'แสดงจำนวนวันลาพักผ่อนที่คุณใช้ไปและเหลืออยู่ในรอบปีงบประมาณปัจจุบัน',
  ABSENCE_STATS_USED_THIS_YEAR: 'จำนวนวันลาที่ใช้ / จำนวนวันลาที่เหลือ',
  ABSENCE_STATS_DAYS_FROM_PREV_YEAR: 'จำนวนวันลาพักผ่อนที่ยกมาจากปีที่แล้ว',
  ABSENCE_STATS_TOTAL_DAYS_THIS_YEAR: 'จำนวนวันลาพักผ่อนทั้งหมด',
  ABSENCE_STATS_MAX_ACCUMULATION: 'จำนวนวันลาพักผ่อนสูงสุดที่สามารถสะสมได้',
  ABSENCE_STATS_LATE_TITLE: 'มาสาย',
  ABSENCE_STATS_UNIT_TIMES: 'ครั้ง',
  ABSENCE_STATS_UNIT_DAYS: 'วัน',

  // absence - History tab
  ABSENCE_HISTORY_SUBTITLE: 'แสดงประวัติการลาทั้งหมดของคุณ',
  ABSENCE_HISTORY_DATE_PREFIX: 'วันที่ลา: ',

  // Meeting
  MEETING_HEADER_TITLE: 'การประชุม',
  MEETING_INCOMING: 'ประชุมเร็วๆ นี้',
  MEETING_LOADING_MEETINGS: 'กำลังโหลดข้อมูลการประชุม',
  MEETING_MENU_TITLE: 'การประชุม',
  MEETING_NO_HISTORY: 'ไม่มีประวัติการประชุม',
  MEETING_NO_INCOMING_MEETINGS: 'ไม่มีการประชุมเร็วๆ นี้',
  MEETING_NO_MEETINGS_TODAY: 'ไม่มีการประชุมวันนี้',
  MEETING_TODAY: 'ประชุมวันนี้',
  MEETING_UNABLE_TO_LOAD_MEETINGS: 'ไม่สามารถโหลดข้อมูลการประชุมได้',
  MEETING_AGENDA_TITLE: 'วาระการประชุม',
  MEETING_AGENDA_SECTION: 'วาระการประชุม',
  MEETING_TOPICS_COUNT: ' วาระ',
  MEETING_LOADING_AGENDA: 'กำลังโหลดวาระการประชุม',
  MEETING_NO_AGENDA: 'ไม่มีวาระการประชุม',
  MEETING_UNABLE_TO_LOAD_AGENDA: 'ไม่สามารถโหลดวาระการประชุมได้',

  // Notice Repair
  NOTICE_REPAIR__MENU_TITLE: 'แจ้งซ่อมสาธารณะ',
  NOTICE_REPAIR__TITLE: 'แจ้งซ่อมสาธารณูปการ',

  NOTICE_REPAIR_ROLE_INFORMER: 'ผู้แจ้งซ่อม',
  NOTICE_REPAIR_ROLE_APPROVE: 'หัวหน้าสาธารณูปการ',
  NOTICE_REPAIR_ROLE_ADMIN: 'เจ้าหน้าที่ธุรการ',
  NOTICE_REPAIR_ROLE_HEADER: 'หัวหน้างาน',
  NOTICE_REPAIR_ROLE_TECHNICIAN: 'ช่างเทคนิค',

  NOTICE_REPAIR_TAB_INFORM: 'แจ้งซ่อม',
  NOTICE_REPAIR_TAB_CURRENT: 'งานปัจจุบัน',
  NOTICE_REPAIR_TAB_HISTORY: 'ประวัติ',
  NOTICE_REPAIR_TAB_PENDING: 'รออนุมัติ',
  NOTICE_REPAIR_TAB_ALL: 'ทั้งหมด',
  NOTICE_REPAIR_TAB_PENDING_RECEIPT: 'รอรับเรื่อง',
  NOTICE_REPAIR_TAB_IN_PROGRESS: 'ดำเนินการ',
  NOTICE_REPAIR_TAB_DONE: 'เสร็จสิ้น',
  NOTICE_REPAIR_TAB_WAITING_ESTIMATE: 'รอประเมิน',
  NOTICE_REPAIR_TAB_ESTIMATED: 'ประเมินแล้ว',
  NOTICE_REPAIR_TAB_REPAIR_RECORD: 'บันทึกการซ่อม',
  NOTICE_REPAIR_TAB_REVIEW: 'พิจารณา',
  NOTICE_REPAIR_TAB_REPAIR_LIST: 'รายการซ่อม',
  NOTICE_REPAIR_TAB_SUPPLY: 'จัดหาวัสดุ',
  NOTICE_REPAIR_TAB_SUPPLY_MATERIAL: 'จัดหาวัสดุ',
  NOTICE_REPAIR_TAB_DEPT_SUPPLY: 'หน่วยงานตอบรับ',
  NOTICE_REPAIR_SUPPLY_VIEW_ALL: 'ดูรายการจัดหาวัสดุ',
  NOTICE_REPAIR_SUPPLY_LIST_TITLE: 'รายการจัดหาวัสดุ',
  NOTICE_REPAIR_TAB_ASSESSMENT: 'ประเมินงาน',
  NOTICE_REPAIR_TAB_ACCEPTANCE: 'ตรวจรับงาน',
  NOTICE_REPAIR_TAB_REJECT_CANNOT_REPAIR: 'ซ่อมไม่ได้',
  NOTICE_REPAIR_TAB_ASSIGNED: 'งานที่ได้รับ',

  NOTICE_REPAIR_LIST_SUBTITLE: 'ติดตามและจัดการรายการแจ้งซ่อม',
  NOTICE_REPAIR_LOADING: 'กำลังโหลดรายการ',
  NOTICE_REPAIR_LOADING_PRIVILEGE: 'กำลังตรวจสอบสิทธิ์',
  NOTICE_REPAIR_NO_ACCESS_TITLE: 'ไม่มีสิทธิ์เข้าใช้งาน',
  NOTICE_REPAIR_NO_ACCESS_MESSAGE: 'บัญชีของคุณไม่มีสิทธิ์ใช้งานระบบแจ้งซ่อมสาธารณูปการ กรุณาติดต่อผู้ดูแลระบบ',
  NOTICE_REPAIR_NO_ITEMS: 'ไม่มีรายการแจ้งซ่อม',
  NOTICE_REPAIR_ERROR_LOAD: 'ไม่สามารถโหลดรายการแจ้งซ่อมได้',
  NOTICE_REPAIR_SELECT_ROLE: 'เลือกบทบาท',
  NOTICE_REPAIR_PENDING_NEW: 'งานใหม่',
  NOTICE_REPAIR_PENDING_HEADER_REJECTED: 'ตีกลับจากหัวหน้างาน',
  NOTICE_REPAIR_REPAIRABLE: 'ซ่อมได้',
  NOTICE_REPAIR_UNREPAIRABLE: 'ซ่อมไม่ได้',

  NOTICE_REPAIR_FORM_NEW_TITLE: 'แจ้งซ่อมใหม่',
  NOTICE_REPAIR_FORM_NEW_SUBTITLE: 'กรุณากรอกรายละเอียดเพื่อแจ้งซ่อมคอมพิวเตอร์หรืออุปกรณ์ต่างๆ',
  NOTICE_REPAIR_FORM_CONFIRM_TITLE: 'ยืนยันการแจ้งซ่อม',
  NOTICE_REPAIR_FORM_CONFIRM_MESSAGE: 'คุณต้องการส่งคำขอแจ้งซ่อมนี้ใช่หรือไม่?',
  NOTICE_REPAIR_FORM_REPAIR_TYPE: 'ประเภทการแจ้ง',
  NOTICE_REPAIR_FORM_REMARK_PLACEHOLDER: 'ระบุข้อมูลเพิ่มเติม (ถ้ามี)',
  NOTICE_REPAIR_FORM_WORK_CATEGORY: 'ประเภทงาน *',
  NOTICE_REPAIR_FORM_PLACE: 'สถานที่ *',
  NOTICE_REPAIR_FORM_DETAIL: 'รายละเอียดปัญหา *',
  NOTICE_REPAIR_FORM_WORK_TYPE: 'ประเภทการซ่อม',
  NOTICE_REPAIR_FORM_PHONE: 'เบอร์โทรศัพท์',
  NOTICE_REPAIR_FORM_BUILDING: 'อาคาร',
  NOTICE_REPAIR_FORM_REMARK: 'หมายเหตุ',
  NOTICE_REPAIR_FORM_SUBMIT: 'ส่งคำขอแจ้งซ่อม',
  NOTICE_REPAIR_FORM_SUCCESS: 'ส่งคำขอแจ้งซ่อมสำเร็จ',
  NOTICE_REPAIR_FORM_ERROR: 'ไม่สามารถส่งคำขอแจ้งซ่อมได้',
  NOTICE_REPAIR_FORM_REQUIRED: 'กรุณากรอกข้อมูลที่จำเป็น',
  NOTICE_REPAIR_FORM_SELECT_CATEGORY: 'เลือกประเภทงาน',
  NOTICE_REPAIR_FORM_SELECT_BUILDING: 'เลือกอาคาร',
  NOTICE_REPAIR_FORM_SELECT_WORK_TYPE: 'เลือกประเภทการซ่อม',

  NOTICE_REPAIR_DETAIL_TITLE: 'ข้อมูลการแจ้งซ่อม',
  NOTICE_REPAIR_DETAIL_NUMBER: 'เลขที่',
  NOTICE_REPAIR_DETAIL_CATEGORY: 'ประเภทงาน',
  NOTICE_REPAIR_DETAIL_PLACE: 'สถานที่',
  NOTICE_REPAIR_DETAIL_BUILDING: 'อาคาร',
  NOTICE_REPAIR_DETAIL_STATUS: 'สถานะ',
  NOTICE_REPAIR_DETAIL_INFORMER: 'ผู้แจ้ง',
  NOTICE_REPAIR_DETAIL_POSITION: 'ตำแหน่ง',
  NOTICE_REPAIR_DETAIL_DEPARTMENT: 'หน่วยงาน',
  NOTICE_REPAIR_DETAIL_DATE: 'วันที่แจ้ง',
  NOTICE_REPAIR_DETAIL_DESCRIPTION: 'รายละเอียด',
  NOTICE_REPAIR_DETAIL_TECHNICIANS: 'ช่างเทคนิค',
  NOTICE_REPAIR_DETAIL_WORK_DATE: 'วันที่ดำเนินการ',
  NOTICE_REPAIR_DETAIL_WORK_RESULT: 'ผลการดำเนินการ',
  NOTICE_REPAIR_DETAIL_PROBLEM: 'ปัญหาที่พบ',
  NOTICE_REPAIR_DETAIL_MATERIALS: 'วัสดุที่ขอเบิก',

  NOTICE_REPAIR_ACTION_APPROVE: 'อนุมัติ',
  NOTICE_REPAIR_ACTION_REJECT: 'ไม่อนุมัติ',
  NOTICE_REPAIR_ACTION_ACCEPT: 'ออกเลขรับ',
  NOTICE_REPAIR_ACTION_EXAMINE_OK: 'งานเรียบร้อย',
  NOTICE_REPAIR_ACTION_EXAMINE_NOT_OK: 'งานไม่เรียบร้อย',

  // Approver (หัวหน้าสาธารณูปการ) detail actions on a new job (status 001)
  NOTICE_REPAIR_ACTION_AGREE: 'เห็นชอบ',
  NOTICE_REPAIR_ACTION_NOT_AGREE: 'ไม่เห็นชอบ',
  NOTICE_REPAIR_ACTION_CANCEL: 'ยกเลิก',
  NOTICE_REPAIR_ACTION_DELETE: 'ลบ',
  NOTICE_REPAIR_ACTION_DELETE_CONFIRM: 'คุณต้องการลบคำขอแจ้งซ่อมนี้ใช่หรือไม่?',
  NOTICE_REPAIR_ACTION_CONFIRM: 'ยืนยัน',
  NOTICE_REPAIR_ACTION_AGREE_CONFIRM: 'ยืนยันการเห็นชอบใบแจ้งซ่อมนี้?',
  NOTICE_REPAIR_ACTION_CANCEL_CONFIRM: 'ยืนยันการยกเลิกใบแจ้งซ่อมนี้?',
  NOTICE_REPAIR_ACTION_NOT_AGREE_CONFIRM: 'ยืนยันการไม่เห็นชอบใบแจ้งซ่อมนี้?',
  NOTICE_REPAIR_ACTION_NOT_AGREE_REASON_LABEL: 'เหตุผลที่ไม่เห็นชอบ',
  NOTICE_REPAIR_ACTION_NOT_AGREE_REASON_PLACEHOLDER: 'กรุณาระบุเหตุผล',
  NOTICE_REPAIR_ACTION_REASON_REQUIRED: 'กรุณาระบุเหตุผล',
  NOTICE_REPAIR_ACTION_SUBMIT: 'ส่ง',
  NOTICE_REPAIR_ACTION_SUCCESS: 'ดำเนินการสำเร็จ',
  NOTICE_REPAIR_ACTION_FAILED: 'ดำเนินการไม่สำเร็จ',

  // Admin (เจ้าหน้าที่บริหารงาน) detail actions on a รอรับเรื่อง job
  NOTICE_REPAIR_ACTION_ADMIN_ACCEPT: 'รับเรื่อง',
  NOTICE_REPAIR_ACTION_ADMIN_REJECT: 'ตีกลับ',
  NOTICE_REPAIR_ACTION_EDIT: 'แก้ไข',
  NOTICE_REPAIR_ACTION_ADMIN_ACCEPT_CONFIRM: 'ยืนยันการรับเรื่องใบแจ้งซ่อมนี้?',
  NOTICE_REPAIR_ACTION_ADMIN_REJECT_CONFIRM: 'ยืนยันการตีกลับใบแจ้งซ่อมนี้?',
  NOTICE_REPAIR_ACTION_ADMIN_REJECT_REASON_LABEL: 'เหตุผลที่ตีกลับ',

  // Admin edit inform form
  NOTICE_REPAIR_EDIT_TITLE: 'แก้ไขข้อมูลแจ้งซ่อม',
  NOTICE_REPAIR_EDIT_SUBMIT: 'บันทึกการแก้ไข',
  NOTICE_REPAIR_EDIT_SUCCESS: 'บันทึกการแก้ไขสำเร็จ',
  NOTICE_REPAIR_EDIT_ERROR: 'ไม่สามารถบันทึกการแก้ไขได้',
  NOTICE_REPAIR_EDIT_LOAD_ERROR: 'ไม่สามารถโหลดข้อมูลสำหรับแก้ไขได้',
  NOTICE_REPAIR_EDIT_CONFIRM_TITLE: 'ยืนยันการแก้ไข',
  NOTICE_REPAIR_EDIT_CONFIRM_MESSAGE: 'คุณต้องการบันทึกการแก้ไขใบแจ้งซ่อมนี้ใช่หรือไม่?',

  // Repair Computer
  REPAIR_COMPUTER_APPROVEMENT: 'อนุมัติครุภัณฑ์คอมพิวเตอร์',
  REPAIR_COMPUTER_APPROVEMENT_DESCRIPTION: 'อนุมัติผลลัพธ์งานซ่อมคอมพิวเตอร์',
  REPAIR_COMPUTER_ASSIGN_CONFIRM: 'ยืนยันการมอบหมาย',
  REPAIR_COMPUTER_BACK_TO_CURRENT_JOB: 'กลับไปยังงานปัจจุบัน',
  REPAIR_COMPUTER_CANNOT_INFORM_JOB: 'ไม่สามารถแจ้งงานได้',
  REPAIR_COMPUTER_CHECKING_PRIVILEGE: 'กำลังตรวจสอบสิทธิ์',
  REPAIR_COMPUTER_CHECKING_REQUEST: 'กำลังตรวจสอบคำขอ',
  REPAIR_COMPUTER_CURRENT_JOB: 'งานปัจจุบัน',
  REPAIR_COMPUTER_CURRENT_JOBS_DESCRIPTION: 'ติดตามคำขอบริการที่ใช้งานอยู่และการบำรุงรักษาที่กำลังดำเนินการ',
  REPAIR_COMPUTER_DELETE_CONFIRM_MESSAGE: 'คุณต้องการลบงานซ่อมคอมพิวเตอร์นี้ใช่หรือไม่?',
  REPAIR_COMPUTER_DETAIL: 'รายละเอียด',
  REPAIR_COMPUTER_DETAIL_LABEL: 'รายละเอียด:',
  REPAIR_COMPUTER_EDIT_JOB: 'แก้ไขงาน',
  REPAIR_COMPUTER_FOREMAN: 'หัวหน้าช่าง',
  REPAIR_COMPUTER_INFORM: 'แจ้ง',
  REPAIR_COMPUTER_INFORM_DATE_LABEL: 'วันที่แจ้ง:',
  REPAIR_COMPUTER_JOB_DELETED_SUCCESS_MESSAGE: 'ลบงานซ่อมสำเร็จ',
  REPAIR_COMPUTER_JOB_DETAIL: 'รายละเอียดงาน',
  REPAIR_COMPUTER_JOB_ID_LABEL: 'รหัสงาน:',
  REPAIR_COMPUTER_JOB_UPDATED_SUCCESS_MESSAGE: 'อัปเดตงานซ่อมคอมพิวเตอร์สำเร็จ',
  REPAIR_COMPUTER_JOBS: 'งาน',
  REPAIR_COMPUTER_LOADING_CURRENT_JOBS: 'กำลังโหลดงานปัจจุบัน',
  REPAIR_COMPUTER_LOADING_DETAIL: 'กำลังโหลดรายละเอียด',
  REPAIR_COMPUTER_LOADING_JOB_DETAIL: 'กำลังโหลดรายละเอียดงาน',
  REPAIR_COMPUTER_LOADING_MANAGE_JOBS: 'กำลังโหลดงานที่จัดการ',
  REPAIR_COMPUTER_LOADING_NEW_JOBS: 'กำลังโหลดงานใหม่',
  REPAIR_COMPUTER_LOADING_QUEUE: 'กำลังโหลดคิว',
  REPAIR_COMPUTER_MANAGE_JOB: 'จัดการงาน',
  REPAIR_COMPUTER_MENU_TITLE: 'แจ้งซ่อมคอมพิวเตอร์',
  REPAIR_COMPUTER_NEW_JOB: 'งานใหม่',
  REPAIR_COMPUTER_NO_CURRENT_JOBS: 'ไม่มีงานปัจจุบัน',
  REPAIR_COMPUTER_NO_JOBS_TO_MANAGE: 'ไม่มีงานที่ต้องจัดการ',
  REPAIR_COMPUTER_NO_NEW_JOBS: 'ไม่มีงานใหม่',
  REPAIR_COMPUTER_NO_WORKER_QUEUE: 'ไม่มีคิวช่าง',
  REPAIR_COMPUTER_PENDING_JOB_TYPE: 'รอการระบุประเภทงาน',
  REPAIR_COMPUTER_PHONE: 'โทรศัพท์',
  REPAIR_COMPUTER_PHONE_LABEL: 'โทรศัพท์:',
  REPAIR_COMPUTER_QUEUE: 'คิว',
  REPAIR_COMPUTER_REJECT_DETAIL_LABEL: 'รายละเอียดการปฏิเสธ:',
  REPAIR_COMPUTER_REQUEST_SUBMITTED_SUCCESS_MESSAGE: 'ส่งคำขอแจ้งซ่อมคอมพิวเตอร์สำเร็จ',
  REPAIR_COMPUTER_SELECT_ROLE: 'เลือกบทบาท',
  REPAIR_COMPUTER_STATUS_LABEL: 'สถานะ:',
  REPAIR_COMPUTER_SUPPLY_CODE: 'รหัสครุภัณฑ์',
  REPAIR_COMPUTER_SUPPLY_CODE_LABEL: 'รหัสครุภัณฑ์:',
  REPAIR_COMPUTER_REPAIR_TYPE_LABEL: 'ประเภทงาน:',
  REPAIR_COMPUTER_TITLE: 'ซ่อมคอมพิวเตอร์',
  REPAIR_COMPUTER_UNABLE_TO_DELETE_JOB: 'ไม่สามารถลบงานซ่อมได้',
  REPAIR_COMPUTER_UNABLE_TO_LOAD_CURRENT_JOBS: 'ไม่สามารถโหลดงานปัจจุบันได้',
  REPAIR_COMPUTER_UNABLE_TO_LOAD_JOB_DETAIL: 'ไม่สามารถโหลดรายละเอียดงานได้',
  REPAIR_COMPUTER_UNABLE_TO_LOAD_MANAGE_JOBS: 'ไม่สามารถโหลดงานที่จัดการได้',
  REPAIR_COMPUTER_UNABLE_TO_LOAD_NEW_JOBS: 'ไม่สามารถโหลดงานใหม่ได้',
  REPAIR_COMPUTER_UNABLE_TO_LOAD_WORKER_QUEUE: 'ไม่สามารถโหลดคิวช่างได้',
  REPAIR_COMPUTER_UNABLE_TO_OPEN_JOB_DETAIL: 'ไม่สามารถเปิดรายละเอียดงานได้',
  REPAIR_COMPUTER_UNABLE_TO_SUBMIT_REQUEST: 'ไม่สามารถส่งคำขอแจ้งซ่อมคอมพิวเตอร์ได้',
  REPAIR_COMPUTER_UNABLE_TO_UPDATE_JOB: 'ไม่สามารถอัปเดตงานซ่อมคอมพิวเตอร์ได้',
  REPAIR_COMPUTER_UPDATE_CONFIRM_MESSAGE: 'คุณต้องการอัปเดตข้อมูลงานซ่อมคอมพิวเตอร์ใช่หรือไม่?',
  REPAIR_COMPUTER_UPDATE_CONFIRM_TITLE: 'ยืนยันการอัปเดต',
  REPAIR_COMPUTER_USER_LABEL: 'ผู้ใช้:',
  REPAIR_COMPUTER_WORKER: 'ช่าง',
  REPAIR_COMPUTER_WORKER_LABEL: 'ช่าง:',
  REPAIR_COMPUTER_VIEW_NEW_WORKER_JOBS_DESCRIPTION: 'ดูงานซ่อมคอมพิวเตอร์ใหม่ที่มอบหมายให้ช่าง',
  REPAIR_COMPUTER_VIEW_WORKER_CURRENT_JOBS_DESCRIPTION: 'ดูงานของช่างที่กำลังดำเนินการอยู่',
  REPAIR_COMPUTER_VIEW_WORKER_HISTORY_DESCRIPTION: 'ดูประวัติงานซ่อมคอมพิวเตอร์ของช่าง',
  REPAIR_COMPUTER_VIEW_FOREMAN_NEW_JOBS_DESCRIPTION: 'ดูงานซ่อมคอมพิวเตอร์ใหม่ที่รอการจัดการ',
  REPAIR_COMPUTER_VIEW_FOREMAN_HISTORY_DESCRIPTION: 'ดูประวัติงานซ่อมคอมพิวเตอร์ของหัวหน้าช่าง',
  REPAIR_COMPUTER_CODE_NOT_AVAILABLE: 'ไม่ระบุ',
  REPAIR_COMPUTER_NEW_REQUEST: 'คำขอซ่อมใหม่',
  REPAIR_COMPUTER_NEW_REQUEST_DESCRIPTION: 'กรุณาให้รายละเอียดเกี่ยวกับปัญหาคอมพิวเตอร์',
  REPAIR_COMPUTER_OPTIONAL: '(ไม่บังคับ)',
  REPAIR_COMPUTER_SUBMIT_REQUEST: 'ส่งคำขอ',
  REPAIR_COMPUTER_REPAIR_HISTORY: 'ประวัติการซ่อม',
  REPAIR_COMPUTER_REPAIR_HISTORY_DESCRIPTION: 'ติดตามคำขอบริการที่เสร็จสมบูรณ์และบันทึกการบำรุงรักษา',
  REPAIR_COMPUTER_WORKER_QUEUE: 'คิวช่างซ่อม',
  REPAIR_COMPUTER_WORKER_QUEUE_DESCRIPTION: 'ติดตามงานที่มอบหมายและปริมาณงานของช่าง',
  // Home "Upcoming Shift" — repair-computer task labels (keyed by role in active-summary)
  REPAIR_COMPUTER_SHIFT_CURRENT_JOB: 'งานที่กำลังดำเนินการ',
  REPAIR_COMPUTER_SHIFT_NEW_JOB: 'งานแจ้งซ่อมใหม่',
  REPAIR_COMPUTER_SHIFT_SUPPLY_APPROVE: 'คำขอเบิกพัสดุรออนุมัติ',
  REPAIR_COMPUTER_SHIFT_RUNNING: 'งานที่มอบหมายให้ช่าง',
  REPAIR_COMPUTER_SHIFT_WORKER_NEW_JOB: 'งานใหม่ที่ได้รับมอบหมาย',
  REPAIR_COMPUTER_SHIFT_WORKER_CURRENT_JOB: 'งานที่กำลังดำเนินการ',
  REPAIR_COMPUTER_SHIFT_SUPPLY_WAIT: 'รออนุมัติเบิกพัสดุ',
  REPAIR_COMPUTER_TOTAL_JOBS: 'งานทั้งหมด',
  REPAIR_COMPUTER_ACTIVE_LABEL: 'Active',
  REPAIR_COMPUTER_ACTIVE_JOBS_PREFIX: 'Active Jobs: ',

  // Calendar
  CALENDAR_DESCRIPTION: 'หน้านี้คือหน้าปฏิทิน',
  CALENDAR_TITLE: 'ปฏิทิน',
  CALENDAR_SUBTITLE: 'แสดงกำหนดการต่างๆ ของผู้บริหาร',

  // Person Search
  PERSON_SEARCH_DESCRIPTION: 'หน้านี้คือหน้าค้นหาบุคลากร',
  PERSON_SEARCH_TITLE: 'ค้นหาบุคลากร',
  PERSON_SEARCH_SUBTITLE: 'ค้นหาบุคลากรในคณะฯ',

  // Examiner / Examinar
  EXAMINER_MENU_TITLE: 'ตารางคุมสอบ',
  EXAMINAR_HEADER_TITLE: 'ตารางคุมสอบ',
  EXAMINAR_HEADER_SUBTITLE: 'แสดงตารางคุมสอบของคุณตามรอบ',
  EXAMINAR_DETAIL_HEADER_TITLE: 'รายละเอียดการสอบ',
  EXAMINAR_FILTER_YEAR: 'ปีการศึกษา',
  EXAMINAR_FILTER_TERM: 'ภาคการศึกษา',
  EXAMINAR_FILTER_PERIOD: 'ช่วงการสอบ',
  EXAMINAR_UPCOMING_LABEL: 'ตารางคุมสอบที่กำลังมาถึง',
  EXAMINAR_VIEW_DETAILS: 'ดูรายละเอียด',
  EXAMINAR_VENUE_LABEL: 'สถานที่สอบ',
  EXAMINAR_SUBJECT_LIST_HEADING: 'รายวิชาสอบ',
  EXAMINAR_PARTNERS_HEADING: 'ผู้คุมสอบ',
  EXAMINAR_LOADING: 'กำลังโหลดตารางคุมสอบ...',
  EXAMINAR_NO_EXAMS: 'ไม่พบตารางคุมสอบ',
  EXAMINAR_UNABLE_TO_LOAD: 'ไม่สามารถโหลดข้อมูลตารางคุมสอบได้',
  EXAMINAR_TERM_1: 'ภาคการศึกษาที่ 1',
  EXAMINAR_TERM_2: 'ภาคการศึกษาที่ 2',
  EXAMINAR_TERM_SUMMER: 'ภาคฤดูร้อน',
  EXAMINAR_PERIOD_MIDTERM: 'กลางภาค',
  EXAMINAR_PERIOD_FINAL: 'ปลายภาค',
  EXAMINAR_PERIOD_MIDTERM_FULL: 'การสอบกลางภาค',
  EXAMINAR_PERIOD_FINAL_FULL: 'การสอบปลายภาค',
  EXAMINAR_STATUS_PAST: 'ผ่านไปแล้ว',
  EXAMINAR_STATUS_TODAY: 'วันนี้',
  EXAMINAR_STATUS_INCOMING: 'กำลังมาถึง',
  EXAMINAR_SUBJECT_ID_PREFIX: 'รหัส: ',
  EXAMINAR_STUDENTS_SUFFIX: ' นักศึกษา',
  EXAMINAR_SECTION_PREFIX: 'ตอน: ',
  EXAMINAR_SUBJECTS_COUNT: ' วิชา',
  EXAMINAR_STAFF_COUNT: ' คน',
  EXAMINAR_NO_SUBJECTS: 'ไม่มีรายวิชา',
  EXAMINAR_NO_STAFF: 'ไม่มีรายชื่อผู้คุมสอบ',
  EXAMINAR_DURATION_HOUR: 'ชม.',
  EXAMINAR_DURATION_MINUTE: 'น.',

  // Timestamp
  TIMESTAMP_DESCRIPTION: 'หน้านี้คือหน้าลืมลงเวลา',
  TIMESTAMP_TITLE: 'การลงเวลา',
  TIMESTAMP_FORGOT_TAB: 'ลืมลงเวลา',
  TIMESTAMP_LIST_SUBTITLE: 'รายการคำขอลืมลงเวลา',
  TIMESTAMP_FORGOT_HISTORY_SUBTITLE: 'ประวัติการลืมลงเวลา',

  // Timestamp - approval (boss inbox)
  TIMESTAMP_APPROVE_TAB: 'รับรอง',
  TIMESTAMP_APPROVE_TITLE: 'รับรองการลืมลงเวลา',
  TIMESTAMP_APPROVE_SUBTITLE: 'รายการรอการรับรอง',
  TIMESTAMP_APPROVE_DETAIL_SUBTITLE: 'รายละเอียดคำขอ',
  TIMESTAMP_APPROVE_EMPTY: 'ไม่มีรายการรอการรับรอง',
  TIMESTAMP_APPROVE_PENDING_TAB: 'รอการรับรอง',
  TIMESTAMP_APPROVE_HISTORY_TAB: 'ประวัติการรับรอง',
  TIMESTAMP_APPROVE_HISTORY_EMPTY: 'ไม่มีประวัติการพิจารณา',
  TIMESTAMP_APPROVE_STATUS_APPROVED: 'รับรองแล้ว',
  TIMESTAMP_APPROVE_STATUS_REJECTED: 'ไม่รับรอง',
  TIMESTAMP_APPROVE_STATUS_PENDING: 'รออนุมัติ',
  TIMESTAMP_APPROVE_DECISION_DATE_LABEL: 'วันที่พิจารณา',
  TIMESTAMP_APPROVE_COMMENT_LABEL: 'ความเห็นผู้อนุมัติ',
  TIMESTAMP_RECORD_INFO_SECTION: 'ข้อมูลการลืมลงเวลา',
  TIMESTAMP_APPROVE_ACCEPT: 'รับรอง',
  TIMESTAMP_APPROVE_ACCEPT_REASON: 'รับรองการลงเวลา',
  TIMESTAMP_APPROVE_REJECT: 'ไม่รับรอง',
  TIMESTAMP_APPROVE_REQUESTER_LABEL: 'ผู้ยื่นคำขอ',
  TIMESTAMP_APPROVE_POSITION_LABEL: 'ตำแหน่ง',
  TIMESTAMP_APPROVE_DEPT_LABEL: 'หน่วยงาน',
  TIMESTAMP_APPROVE_TYPE_LABEL: 'ประเภท',
  TIMESTAMP_APPROVE_STAMP_DATE_LABEL: 'วันที่ลืมลงเวลา',
  TIMESTAMP_APPROVE_WRITE_DATE_LABEL: 'วันที่ยื่นคำขอ',
  TIMESTAMP_APPROVE_IN_TIME_LABEL: 'เวลาเข้า',
  TIMESTAMP_APPROVE_OUT_TIME_LABEL: 'เวลาออก',
  TIMESTAMP_APPROVE_REASON_LABEL: 'เหตุผล',
  TIMESTAMP_APPROVE_NOTE_LABEL: 'ความเห็น',
  TIMESTAMP_APPROVE_NOTE_PLACEHOLDER: 'กรอกความเห็น',
  TIMESTAMP_APPROVE_NOTE_REQUIRED: 'กรุณากรอกความเห็น',
  TIMESTAMP_APPROVE_SUBMIT: 'บันทึกผลการพิจารณา',
  TIMESTAMP_APPROVE_SUBMIT_SUCCESS: 'บันทึกผลการพิจารณาเรียบร้อย',
  TIMESTAMP_APPROVE_SUBMIT_ERROR: 'บันทึกผลการพิจารณาล้มเหลว',
  TIMESTAMP_APPROVE_CONFIRM_TITLE: 'ยืนยันการบันทึก',
  TIMESTAMP_APPROVE_CONFIRM_MESSAGE: 'คุณต้องการบันทึกผลการพิจารณานี้ใช่หรือไม่?',
  TIMESTAMP_APPROVE_CONFIRM_ACTION: 'ยืนยัน',

  // Timestamp - calendar tab
  TIMESTAMP_CALENDAR_TAB: 'ปฏิทินลงเวลา',
  TIMESTAMP_CALENDAR_TITLE: 'ปฏิทินการลงเวลา',
  TIMESTAMP_CALENDAR_IN: 'เวลาเข้า',
  TIMESTAMP_CALENDAR_OUT: 'เวลาออก',
  TIMESTAMP_CALENDAR_LEGEND_PRESENT: 'มาทำงาน',
  TIMESTAMP_CALENDAR_LEGEND_INCOMPLETE: 'ลงเวลาไม่ครบ',
  TIMESTAMP_CALENDAR_LEGEND_ABSENT: 'ขาดงาน',
  TIMESTAMP_CALENDAR_LEGEND_LEAVE: 'ลา',
  TIMESTAMP_CALENDAR_LEGEND_HOLIDAY: 'วันหยุด',
  TIMESTAMP_CALENDAR_LEGEND_LATE: 'มาสาย',
  TIMESTAMP_CALENDAR_NO_DATA: 'ยังไม่มีข้อมูลการลงเวลาในเดือนนี้',
  TIMESTAMP_CALENDAR_SELECTED_NO_DATA: 'ไม่มีข้อมูลการลงเวลาในวันนี้',
  TIMESTAMP_CALENDAR_PRESENT_DESC: 'มาทำงานตามปกติ',
  TIMESTAMP_CALENDAR_HINT: 'แตะที่วันเพื่อดูรายละเอียดการลงเวลา',
  TIMESTAMP_CALENDAR_NO_TIME_DATA: 'ยังไม่มีข้อมูลเวลาเข้า-ออกจากระบบ',
  TIMESTAMP_CALENDAR_MAKE_REQUEST: 'ทำเรื่องลืมลงเวลา',
  TIMESTAMP_CALENDAR_LATE: 'มาสาย',
  TIMESTAMP_CALENDAR_LATE_SHORT: 'สาย',
  TIMESTAMP_CALENDAR_LATE_DESC: 'เข้างานสาย',
  TIMESTAMP_CALENDAR_LATE_COUNT_LABEL: 'จำนวนมาสาย',
  TIMESTAMP_CALENDAR_LATE_COUNT_PERIOD: 'ในปีงบประมาณนี้',

  // Timestamp - common
  TIMESTAMP_STAMP_IN: 'ลืมลงเวลาเข้า',
  TIMESTAMP_STAMP_OUT: 'ลืมลงเวลาออก',
  TIMESTAMP_STAMP_ALL: 'ขาดงาน',
  TIMESTAMP_ACTION_REQUIRED: 'ต้องดำเนินการ',
  TIMESTAMP_PENDING_BADGE: 'รออนุมัติ',
  TIMESTAMP_APPROVED_BADGE: 'อนุมัติแล้ว',
  TIMESTAMP_REJECTED_BADGE: 'ปฏิเสธแล้ว',
  TIMESTAMP_REASON_LABEL: 'เหตุผลการแก้ไข',

  // Timestamp - index screen
  TIMESTAMP_APPEAL_DOCUMENT: 'กรุณาไปที่พอร์ทัล HR เพื่อยื่นอุทธรณ์พร้อมเอกสารประกอบ',
  TIMESTAMP_NOTE_LABEL: 'คำแนะนำ',
  TIMESTAMP_NOTE_TEXT: 'หากคุณลืมลงเวลาเข้างานหรือออกงาน คุณสามารถกรอกแบบฟอร์มคำขอลืมลงเวลาภายใน 3 วันหลังจากวันที่ลืมลงเวลาได้ที่หน้านี้',
  TIMESTAMP_COMPANY_CYCLE_LABEL: 'ในรอบปีงบประมาณ',

  // Timestamp - detail screen
  TIMESTAMP_CONTEXT_IN_TITLE: 'ลืมลงเวลาเข้างาน?',
  TIMESTAMP_CONTEXT_OUT_TITLE: 'ลืมลงเวลาออกงาน?',
  TIMESTAMP_CONTEXT_IN_DESC: 'เลือกเวลาที่ถูกต้องที่คุณลงเวลาเข้างานในวันนั้น',
  TIMESTAMP_CONTEXT_OUT_DESC: 'เลือกเวลาที่ถูกต้องที่คุณลงเวลาออกงานในวันนั้น',
  TIMESTAMP_CONTEXT_DEFAULT_DESC: 'กรอกแบบฟอร์มด้านล่างเพื่อส่งคำขอลืมลงเวลา',
  TIMESTAMP_FIELD_APPROVER: 'ผู้อนุมัติ',
  TIMESTAMP_SELECT_APPROVER: 'เลือกผู้อนุมัติ',
  TIMESTAMP_FIELD_EMPLOYEE_NAME: 'ชื่อพนักงาน',
  TIMESTAMP_FIELD_ORIGINAL_DATE: 'วันที่เดิม',
  TIMESTAMP_FIELD_CORRECTED_TIME: 'เวลาที่แก้ไข',
  TIMESTAMP_HOUR: 'ชั่วโมง',
  TIMESTAMP_MINUTE: 'นาที',
  TIMESTAMP_SELECT_TIME: 'เลือกเวลา',
  TIMESTAMP_DONE: 'เสร็จสิ้น',
  TIMESTAMP_IN_HINT: 'เวลาเริ่มงาน 07:00 - 08:45 น.',
  TIMESTAMP_OUT_HINT: 'เวลาเลิกงาน 16:30 - 20:30 น.',
  TIMESTAMP_GUIDANCE_NOTE: 'คำขอต้องส่งภายในวันศุกร์ เวลา 17:00 น. เพื่อให้ทันรอบเงินเดือน',
  TIMESTAMP_REASON_PLACEHOLDER: 'กรอกเหตุผล',
  TIMESTAMP_APPROVER_REQUIRED: 'กรุณาเลือกผู้อนุมัติ',
  TIMESTAMP_TIME_REQUIRED: 'กรุณาเลือกเวลา',
  TIMESTAMP_REASON_REQUIRED: 'กรุณากรอกเหตุผล',
  TIMESTAMP_SUBMIT: 'ส่งคำขอ',
  TIMESTAMP_SUBMITTING: 'กำลังส่ง...',
  TIMESTAMP_REMOVING: 'กำลังลบ...',
  TIMESTAMP_APPROVER_LIST_TITLE: 'รายชื่อผู้อนุมัติ',
  TIMESTAMP_CONFIRM_SUBMIT_TITLE: 'ยืนยันการส่งคำขอ',
  TIMESTAMP_CONFIRM_SUBMIT_MESSAGE: 'คุณต้องการส่งคำขอลืมลงเวลานี้ใช่หรือไม่?',
  TIMESTAMP_CONFIRM_REMOVE_TITLE: 'ยืนยันการลบ',
  TIMESTAMP_CONFIRM_REMOVE_MESSAGE: 'คุณต้องการลบคำขอลืมลงเวลานี้ใช่หรือไม่?',

  // Timestamp - history screen
  TIMESTAMP_HISTORY_SUBTITLE: 'ดูคำขอลงเวลาที่ดำเนินการเสร็จสิ้นแล้ว',
  TIMESTAMP_TOTAL_APPROVED: 'อนุมัติทั้งหมด',
  TIMESTAMP_TOTAL_REJECTED: 'ปฏิเสธทั้งหมด',
  TIMESTAMP_END_OF_HISTORY: 'สิ้นสุดประวัติ',

  // Timestamp - history detail screen
  TIMESTAMP_DETAIL_TITLE: 'รายละเอียดการลงเวลา',
  TIMESTAMP_TYPE_LABEL: 'ประเภท',
  TIMESTAMP_STAMP_IN_TYPE: 'ลืมลงเวลาเข้างาน',
  TIMESTAMP_STAMP_OUT_TYPE: 'ลืมลงเวลาเลิกงาน',
  TIMESTAMP_APPEAL_DATE: 'วันที่ยื่น',
  TIMESTAMP_TIMESTAMP_DATETIME: 'วันและเวลาลงเวลา',
  TIMESTAMP_TIMESTAMP_TYPE: 'ประเภทการลงเวลา',

  // Modal
  MODAL_TITLE: 'หน้าต่างโมดัล',
} as const;
