export const  TYPE_MEETING_TODAY = 't';
export const  TYPE_MEETING_INCOMING = 'c';
export const  TYPE_MEETING_HISTORY = 'p';

export const MEETING_TYPE = {
  TODAY: TYPE_MEETING_TODAY,
  INCOMING: TYPE_MEETING_INCOMING,
  SHARED_HISTORY: TYPE_MEETING_HISTORY,
};